const leagueData = {
    worldCup: {
        label: 'Copa do Mundo',
        teams: [
            { image: 'img/paises/alemanha.svg', name: 'Alemanha', strength: 91, nation: 'Alemanha' },
            { image: 'img/paises/inglaterra.svg', name: 'Inglaterra', strength: 90, nation: 'Inglaterra' },
            { image: 'img/paises/franca.svg', name: 'França', strength: 89, nation: 'França' },
            { image: 'img/paises/italia.svg', name: 'Itália', strength: 88, nation: 'Itália' },
            { image: 'img/paises/espanha.svg', name: 'Espanha', strength: 87, nation: 'Espanha' },
            { image: 'img/paises/portugal.svg', name: 'Portugal', strength: 86, nation: 'Portugal' },
            { image: 'img/paises/holanda.svg', name: 'Holanda', strength: 85, nation: 'Países Baixos' },
            { image: 'img/paises/belgica.svg', name: 'Bélgica', strength: 84, nation: 'Bélgica' },
            { image: 'img/paises/croacia.svg', name: 'Croácia', strength: 83, nation: 'Croácia' },
            { image: 'img/paises/suica.svg', name: 'Suíça', strength: 82, nation: 'Suíça' },
            { image: 'img/paises/suecia.svg', name: 'Suécia', strength: 81, nation: 'Suécia' },
            { image: 'img/paises/polonia.svg', name: 'Polônia', strength: 80, nation: 'Polônia' },
            { image: 'img/paises/austria.svg', name: 'Áustria', strength: 79, nation: 'Áustria' },
            { image: 'img/paises/dinamarca.svg', name: 'Dinamarca', strength: 78, nation: 'Dinamarca' },
            { image: 'img/paises/russia.svg', name: 'Rússia', strength: 77, nation: 'Rússia' },
            { image: 'img/paises/ucrania.svg', name: 'Ucrânia', strength: 76, nation: 'Ucrânia' },
            { image: 'img/paises/turquia.svg', name: 'Turquia', strength: 75, nation: 'Turquia' },
            { image: 'img/paises/tcheca.svg', name: 'República Tcheca', strength: 74, nation: 'República Tcheca' },
            { image: 'img/paises/escocia.svg', name: 'Escócia', strength: 73, nation: 'Escócia' },
            { image: 'img/paises/servia.svg', name: 'Sérvia', strength: 72, nation: 'Sérvia' },
            { image: 'img/paises/gales.svg', name: 'País de Gales', strength: 71, nation: 'País de Gales' },
            { image: 'img/paises/irlanda.svg', name: 'Irlanda', strength: 70, nation: 'Irlanda' },
            { image: 'img/paises/irlandanorte.svg', name: 'Irlanda do Norte', strength: 69, nation: 'Irlanda do Norte' },
            { image: 'img/paises/romenia.svg', name: 'Romênia', strength: 68, nation: 'Romênia' },
            { image: 'img/paises/grecia.svg', name: 'Grécia', strength: 67, nation: 'Grécia' },
            { image: 'img/paises/hungria.svg', name: 'Hungria', strength: 66, nation: 'Hungria' },
            { image: 'img/paises/bulgaria.svg', name: 'Bulgária', strength: 65, nation: 'Bulgária' },
            { image: 'img/paises/noruega.svg', name: 'Noruega', strength: 64, nation: 'Noruega' },
            { image: 'img/paises/eslovaquia.svg', name: 'Eslováquia', strength: 63, nation: 'Eslováquia' },
            { image: 'img/paises/eslovenia.svg', name: 'Eslovênia', strength: 62, nation: 'Eslovênia' },
            { image: 'img/paises/bosnia.svg', name: 'Bósnia e Herzegovina', strength: 61, nation: 'Bósnia e Herzegovina' },
            { image: 'img/paises/finlandia.svg', name: 'Finlândia', strength: 60, nation: 'Finlândia' },
            { image: 'img/paises/islandia.svg', name: 'Islândia', strength: 59, nation: 'Islândia' },
            { image: 'img/paises/brasil.svg', name: 'Brasil', strength: 92, nation: 'Brasil' },
            { image: 'img/paises/argentina.svg', name: 'Argentina', strength: 91, nation: 'Argentina' },
            { image: 'img/paises/uruguai.svg', name: 'Uruguai', strength: 90, nation: 'Uruguai' },
            { image: 'img/paises/mexico.svg', name: 'México', strength: 84, nation: 'México' },
            { image: 'img/paises/usa.svg', name: 'Estados Unidos', strength: 83, nation: 'Estados Unidos' },
            { image: 'img/paises/canada.svg', name: 'Canadá', strength: 82, nation: 'Canadá' },
            { image: 'img/paises/colombia.svg', name: 'Colômbia', strength: 81, nation: 'Colômbia' },
            { image: 'img/paises/chile.svg', name: 'Chile', strength: 80, nation: 'Chile' },
            { image: 'img/paises/paraguay.svg', name: 'Paraguai', strength: 79, nation: 'Paraguai' },
            { image: 'img/paises/equador.svg', name: 'Equador', strength: 78, nation: 'Equador' },
            { image: 'img/paises/peru.svg', name: 'Peru', strength: 77, nation: 'Peru' },
            { image: 'img/paises/costarica.svg', name: 'Costa Rica', strength: 76, nation: 'Costa Rica' },
            { image: 'img/paises/jamaica.svg', name: 'Jamaica', strength: 75, nation: 'Jamaica' },
            { image: 'img/paises/honduras.svg', name: 'Honduras', strength: 74, nation: 'Honduras' },
            { image: 'img/paises/panama.svg', name: 'Panamá', strength: 73, nation: 'Panamá' },
            { image: 'img/paises/salvador.svg', name: 'El Salvador', strength: 72, nation: 'El Salvador' },
            { image: 'img/paises/haiti.svg', name: 'Haiti', strength: 71, nation: 'Haiti' },
            { image: 'img/paises/curacau.svg', name: 'Curaçau', strength: 70, nation: 'Curaçau' },
            { image: 'img/paises/vietna.svg', name: 'Vietnã', strength: 69, nation: 'Trindade e Tobago' },
            { image: 'img/paises/nigeria.svg', name: 'Nigéria', strength: 68, nation: 'Nigéria' },
            { image: 'img/paises/marrocos.svg', name: 'Marrocos', strength: 67, nation: 'Marrocos' },
            { image: 'img/paises/senegal.svg', name: 'Senegal', strength: 66, nation: 'Senegal' },
            { image: 'img/paises/camaroes.svg', name: 'Camarões', strength: 65, nation: 'Camarões' },
            { image: 'img/paises/gana.svg', name: 'Gana', strength: 64, nation: 'Gana' },
            { image: 'img/paises/egito.svg', name: 'Egito', strength: 63, nation: 'Egito' },
            { image: 'img/paises/argelia.svg', name: 'Argélia', strength: 62, nation: 'Argélia' },
            { image: 'img/paises/tunisia.svg', name: 'Tunísia', strength: 61, nation: 'Tunísia' },
            { image: 'img/paises/africa.svg', name: 'África do Sul', strength: 60, nation: 'África do Sul' },
            { image: 'img/paises/costamarfim.svg', name: 'Costa do Marfim', strength: 59, nation: 'Costa do Marfim' },
            { image: 'img/paises/angola.svg', name: 'Angola', strength: 58, nation: 'Angola' },
            { image: 'img/paises/caboverde.svg', name: 'Cabo Verde', strength: 57, nation: 'Cabo Verde' },
            { image: 'img/paises/congo.svg', name: 'RD Congo', strength: 56, nation: 'RD Congo' },
            { image: 'img/paises/mali.svg', name: 'Mali', strength: 55, nation: 'Mali' },
            { image: 'img/paises/somalia.svg', name: 'Somalia', strength: 55, nation: 'Mali' },
            { image: 'img/paises/zambia.svg', name: 'Zâmbia', strength: 54, nation: 'Zâmbia' },
            { image: 'img/paises/japao.svg', name: 'Japão', strength: 80, nation: 'Japão' },
            { image: 'img/paises/coreiasul.svg', name: 'Coreia do Sul', strength: 79, nation: 'Coreia do Sul' },
            { image: 'img/paises/australia.svg', name: 'Austrália', strength: 78, nation: 'Austrália' },
            { image: 'img/paises/arabia.svg', name: 'Arábia Saudita', strength: 77, nation: 'Arábia Saudita' },
            { image: 'img/paises/ira.svg', name: 'Irã', strength: 76, nation: 'Irã' },
            { image: 'img/paises/china.svg', name: 'China', strength: 75, nation: 'China' },
            { image: 'img/paises/coreianorte.svg', name: 'Coreia do Norte', strength: 74, nation: 'Coreia do Norte' },
            { image: 'img/paises/emiradosarabes.svg', name: 'Emirados Árabes Unidos', strength: 73, nation: 'Emirados Árabes Unidos' },
            { image: 'img/paises/catar.svg', name: 'Catar', strength: 72, nation: 'Catar' },
            { image: 'img/paises/iraque.svg', name: 'Iraque', strength: 71, nation: 'Iraque' },
            { image: 'img/paises/usbequistao.svg', name: 'Uzbequistão', strength: 70, nation: 'Uzbequistão' },
            { image: 'img/paises/jordania.svg', name: 'Jordânia', strength: 69, nation: 'Jordânia' },
            { image: 'img/paises/zelandia.svg', name: 'Nova Zelândia', strength: 68, nation: 'Nova Zelândia' },
            { image: 'img/paises/afeganistao.svg', name: 'Afeganistão', strength: 67, nation: 'Afeganistão' },
            { image: 'img/paises/albania.svg', name: 'Albania', strength: 66, nation: 'Albania' },
            { image: 'img/paises/andorra.svg', name: 'Andorra', strength: 65, nation: 'Andorra' },
            { image: 'img/paises/armenia.svg', name: 'Armênia', strength: 64, nation: 'Armênia' },
            { image: 'img/paises/azerbajao.svg', name: 'Azerbaijão', strength: 64, nation: 'Azerbaijão' },
            { image: 'img/paises/bangladesh.svg', name: 'Bangladesh', strength: 64, nation: 'Bangladesh' },
            { image: 'img/paises/bolivia.svg', name: 'Bolívia', strength: 64, nation: 'Bolívia' },
            { image: 'img/paises/estonia.svg', name: 'Estônia', strength: 64, nation: 'Estônia' },
            { image: 'img/paises/etiopia.svg', name: 'Etiópia', strength: 64, nation: 'Etiópia' },
            { image: 'img/paises/filipinas.svg', name: 'Filipinas', strength: 64, nation: 'Filipinas' },
            { image: 'img/paises/gambia.svg', name: 'Gâmbia', strength: 64, nation: 'Gâmbia' },
            { image: 'img/paises/guatemala.svg', name: 'Guatemala', strength: 64, nation: 'Guatemala' },
            { image: 'img/paises/hongkong.svg', name: 'Hong Kong', strength: 64, nation: 'Hong Kong' },
            { image: 'img/paises/india.svg', name: 'India', strength: 64, nation: 'India' },
            { image: 'img/paises/israel.svg', name: 'Israel', strength: 64, nation: 'Israel' },
            { image: 'img/paises/libano.svg', name: 'Líbano', strength: 64, nation: 'Líbano' },
            { image: 'img/paises/lituania.svg', name: 'Lituânia', strength: 64, nation: 'Lituânia' },
            { image: 'img/paises/macedonia.svg', name: 'Macedônia do Norte', strength: 64, nation: 'Macedônia do Norte' },
            { image: 'img/paises/madagascar.svg', name: 'Madagascar', strength: 64, nation: 'Madagascar' },
            { image: 'img/paises/mocambique.svg', name: 'Moçambique', strength: 64, nation: 'Moçambique' },
            { image: 'img/paises/moldavia.svg', name: 'Moldávia', strength: 64, nation: 'Moldávia' },
            { image: 'img/paises/mongolia.svg', name: 'Mongólia', strength: 64, nation: 'Mongólia' },
            { image: 'img/paises/nepal.svg', name: 'Nepal', strength: 64, nation: 'Nepal' },
            { image: 'img/paises/nicaragua.svg', name: 'Nicaragua', strength: 64, nation: 'Nicaragua' },
            { image: 'img/paises/oman.svg', name: 'Oman', strength: 64, nation: 'Oman' },
            { image: 'img/paises/paquistao.svg', name: 'Paquistão', strength: 64, nation: 'Paquistão' },
            { image: 'img/paises/portorico.svg', name: 'Porto Rico', strength: 64, nation: 'Porto Rico' },
            { image: 'img/paises/reinounido.svg', name: 'Reino Unido', strength: 64, nation: 'Reino Unido' },
            { image: 'img/paises/singapura.svg', name: 'Singapura', strength: 64, nation: 'Singapura' },
            { image: 'img/paises/siria.svg', name: 'Síria', strength: 64, nation: 'Síria' },
            { image: 'img/paises/srilanka.svg', name: 'Sri Lanka', strength: 64, nation: 'Sri Lanka' },
            { image: 'img/paises/sudao.svg', name: 'Sudão', strength: 64, nation: 'Sudão' },
            { image: 'img/paises/suriname.svg', name: 'Suriname', strength: 64, nation: 'Suriname' },
            { image: 'img/paises/tailandia.svg', name: 'Tailândia', strength: 64, nation: 'Tailândia' },
            { image: 'img/paises/taiwan.svg', name: 'Taiwan', strength: 64, nation: 'Taiwan' },
            { image: 'img/paises/uganda.svg', name: 'Uganda', strength: 64, nation: 'Uganda' },
            { image: 'img/paises/venezuela.svg', name: 'Venezuela', strength: 64, nation: 'Venezuela' }
        ]
    },
    libertadores: {
        label: 'Libertadores',
        leagues: ['brasil', 'argentina', 'bolivia', 'chile', 'colombia', 'equador', 'paraguai', 'peru', 'uruguai', 'venezuela']
    },
    brasil: {
        label: 'Liga Brasil',
        teams: [
            { image: 'img/Brasil/fla_br.png', name: 'Flamengo', strength: 88, nation: 'Brasil' },
            { image: 'img/Brasil/bota_br.png', name: 'Botafogo', strength: 88, nation: 'Brasil' },
            { image: 'img/Brasil/pal_br.png', name: 'Palmeiras', strength: 87, nation: 'Brasil' },
            { image: 'img/Brasil/forta_br.png', name: 'Fortaleza', strength: 85, nation: 'Brasil' },
            { image: 'img/Brasil/sp_br.png', name: 'São Paulo', strength: 84, nation: 'Brasil' },
            { image: 'img/Brasil/inter_br.svg', name: 'Internacional', strength: 84, nation: 'Brasil' },
            { image: 'img/Brasil/mineiro_br.png', name: 'Atlético Mineiro', strength: 83, nation: 'Brasil' },
            { image: 'img/Brasil/cru_br.png', name: 'Cruzeiro', strength: 83, nation: 'Brasil' },
            { image: 'img/Brasil/bahia_br.png', name: 'Bahia', strength: 83, nation: 'Brasil' },
            { image: 'img/Brasil/cor_br.png', name: 'Corinthians', strength: 82, nation: 'Brasil' },
            { image: 'img/Brasil/vasco_br.png', name: 'Vasco', strength: 81, nation: 'Brasil' },
            { image: 'img/Brasil/gremio_br.png', name: 'Grêmio', strength: 81, nation: 'Brasil' },
            { image: 'img/Brasil/flu_br.png', name: 'Fluminense', strength: 80, nation: 'Brasil' },
            { image: 'img/Brasil/santos_br.png', name: 'Santos', strength: 79, nation: 'Brasil' },
            { image: 'img/Brasil/vitoria_br.png', name: 'Vitória', strength: 77, nation: 'Brasil' },
            { image: 'img/Brasil/cri_br.png', name: 'Criciúma', strength: 76, nation: 'Brasil' },
            { image: 'img/Brasil/juve_br.png', name: 'Juventude', strength: 76, nation: 'Brasil' },
            { image: 'img/Brasil/cuia_br.png', name: 'Cuiaba', strength: 75, nation: 'Brasil' },
            { image: 'img/Brasil/ceara_br.png', name: 'Ceará', strength: 75, nation: 'Brasil' },
            { image: 'img/Brasil/mira_br.png', name: 'Mirassol', strength: 74, nation: 'Brasil' }
        ]
    },
    italia: {
        label: 'Liga Itália',
        teams: [
            { image: 'img/Italia/juventus.svg', name: 'Juventus', strength: 87, nation: 'Itália' },
            { image: 'img/Italia/internazionale.svg', name: 'Inter de Milão', strength: 88, nation: 'Itália' },
            { image: 'img/Italia/milan.svg', name: 'Milan', strength: 85, nation: 'Itália' },
            { image: 'img/Italia/napoli.svg', name: 'Napoli', strength: 86, nation: 'Itália' },
            { image: 'img/Italia/roma.svg', name: 'Roma', strength: 83, nation: 'Itália' },
            { image: 'img/Italia/lazio.svg', name: 'Lazio', strength: 82, nation: 'Itália' },
            { image: 'img/Italia/atalanta.svg', name: 'Atalanta', strength: 84, nation: 'Itália' },
            { image: 'img/Italia/fiorentina.svg', name: 'Fiorentina', strength: 80, nation: 'Itália' },
            { image: 'img/Italia/bologna.svg', name: 'Bologna', strength: 81, nation: 'Itália' },
            { image: 'img/Italia/torino.svg', name: 'Torino', strength: 78, nation: 'Itália' },
            { image: 'img/Italia/genoa.svg', name: 'Genoa', strength: 77, nation: 'Itália' },
            { image: 'img/Italia/monza.svg', name: 'Monza', strength: 76, nation: 'Itália' },
            { image: 'img/Italia/udinese.svg', name: 'Udinese', strength: 76, nation: 'Itália' },
            { image: 'img/Italia/verona.png', name: 'Hellas Verona', strength: 75, nation: 'Itália' },
            { image: 'img/Italia/lecce.svg', name: 'Lecce', strength: 75, nation: 'Itália' },
            { image: 'img/Italia/cagliari.svg', name: 'Cagliari', strength: 74, nation: 'Itália' },
            { image: 'img/Italia/empoli.svg', name: 'Empoli', strength: 74, nation: 'Itália' },
            { image: 'img/Italia/parma.svg', name: 'Parma', strength: 74, nation: 'Itália' },
            { image: 'img/Italia/como.svg', name: 'Como', strength: 73, nation: 'Itália' },
            { image: 'img/Italia/venezia.svg', name: 'Venezia', strength: 73, nation: 'Itália' }
        ]
    },
    inglaterra: {
        label: 'Liga Inglaterra',
        teams: [
            { image: 'img/inglaterra/city.svg', name: 'Manchester City', strength: 94, nation: 'Inglaterra' },
            { image: 'img/inglaterra/liverpool.svg', name: 'Liverpool', strength: 91, nation: 'Inglaterra' },
            { image: 'img/inglaterra/chelsea.svg', name: 'Chelsea', strength: 89, nation: 'Inglaterra' },
            { image: 'img/inglaterra/united.svg', name: 'Manchester United', strength: 88, nation: 'Inglaterra' },
            { image: 'img/inglaterra/arsenal.svg', name: 'Arsenal', strength: 90, nation: 'Inglaterra' },
            { image: 'img/inglaterra/tottenham.svg', name: 'Tottenham', strength: 86, nation: 'Inglaterra' },
            { image: 'img/inglaterra/newcastle.svg', name: 'Newcastle', strength: 85, nation: 'Inglaterra' },
            { image: 'img/inglaterra/aston.svg', name: 'Aston Villa', strength: 80, nation: 'Inglaterra' },
            { image: 'img/inglaterra/west.svg', name: 'West Ham', strength: 79, nation: 'Inglaterra' },
            { image: 'img/inglaterra/brighton.svg', name: 'Brighton', strength: 79, nation: 'Inglaterra' },
            { image: 'img/inglaterra/crystal.svg', name: 'Crystal Palace', strength: 78, nation: 'Inglaterra' },
            { image: 'img/inglaterra/fulham.svg', name: 'Fulham', strength: 77, nation: 'Inglaterra' },
            { image: 'img/inglaterra/bour.svg', name: 'Bournemouth', strength: 77, nation: 'Inglaterra' },
            { image: 'img/inglaterra/everton.svg', name: 'Everton', strength: 76, nation: 'Inglaterra' },
            { image: 'img/inglaterra/wolver.svg', name: 'Wolverhampton', strength: 76, nation: 'Inglaterra' },
            { image: 'img/inglaterra/notting.svg', name: 'Nottingham Forest', strength: 76, nation: 'Inglaterra' },
            { image: 'img/inglaterra/brent.svg', name: 'Brentford', strength: 75, nation: 'Inglaterra' },
            { image: 'img/inglaterra/leicester.svg', name: 'Leicester City', strength: 75, nation: 'Inglaterra' },
            { image: 'img/inglaterra/south.svg', name: 'Southampton', strength: 74, nation: 'Inglaterra' },
            { image: 'img/inglaterra/sheffield.svg', name: 'Sheffield United', strength: 73, nation: 'Inglaterra' }
        ]
    },
    franca: {
        label: 'Liga França',
        teams: [
            { image: 'img/franca/paris.svg', name: 'Paris Saint-Germain', strength: 91, nation: 'França' },
            { image: 'img/franca/marseille.svg', name: 'Marseille', strength: 83, nation: 'França' },
            { image: 'img/franca/lyon.svg', name: 'Lyon', strength: 82, nation: 'França' },
            { image: 'img/franca/monaco.svg', name: 'Monaco', strength: 84, nation: 'França' },
            { image: 'img/franca/rennes.svg', name: 'Rennes', strength: 80, nation: 'França' },
            { image: 'img/franca/lille.svg', name: 'Lille', strength: 82, nation: 'França' },
            { image: 'img/franca/nice.svg', name: 'Nice', strength: 79, nation: 'França' },
            { image: 'img/franca/nantes.svg', name: 'Nantes', strength: 78, nation: 'França' },
            { image: 'img/franca/lens.svg', name: 'Lens', strength: 81, nation: 'França' },
            { image: 'img/franca/brest.svg', name: 'Brest', strength: 80, nation: 'França' },
            { image: 'img/franca/metz.svg', name: 'Metz', strength: 77, nation: 'França' },
            { image: 'img/franca/toulouse.svg', name: 'Toulouse', strength: 77, nation: 'França' },
            { image: 'img/franca/stras.svg', name: 'Strasbourg', strength: 76, nation: 'França' },
            { image: 'img/franca/mont.svg', name: 'Montpellier', strength: 76, nation: 'França' },
            { image: 'img/franca/havre.svg', name: 'Le Havre', strength: 75, nation: 'França' },
            { image: 'img/franca/mans.svg', name: 'Le Mans FC', strength: 75, nation: 'França' },
            { image: 'img/franca/auxerre.svg', name: 'Auxerre', strength: 74, nation: 'França' },
            { image: 'img/franca/angers.svg', name: 'Angers', strength: 73, nation: 'França' }
        ]
    },
    alemanha: {
        label: 'Liga Alemanha',
        teams: [
            { image: 'img/alemanha/munique.svg', name: 'Bayern de Munique', strength: 92, nation: 'Alemanha' },
            { image: 'img/alemanha/leverkunsen.svg', name: 'Bayer Leverkusen', strength: 89, nation: 'Alemanha' },
            { image: 'img/alemanha/borussia.svg', name: 'Borussia Dortmund', strength: 86, nation: 'Alemanha' },
            { image: 'img/alemanha/leipzig.svg', name: 'RB Leipzig', strength: 85, nation: 'Alemanha' },
            { image: 'img/alemanha/vfb.svg', name: 'VfB Stuttgart', strength: 83, nation: 'Alemanha' },
            { image: 'img/alemanha/eintacht.svg', name: 'Eintracht Frankfurt', strength: 81, nation: 'Alemanha' },
            { image: 'img/alemanha/freiburg.svg', name: 'Freiburg', strength: 79, nation: 'Alemanha' },
            { image: 'img/alemanha/hoff.svg', name: 'Hoffenheim', strength: 78, nation: 'Alemanha' },
            { image: 'img/alemanha/wolfs.svg', name: 'Wolfsburg', strength: 77, nation: 'Alemanha' },
            { image: 'img/alemanha/boru.svg', name: 'Borussia Mönchengladbach', strength: 77, nation: 'Alemanha' },
            { image: 'img/alemanha/werder.svg', name: 'Werder Bremen', strength: 76, nation: 'Alemanha' },
            { image: 'img/alemanha/union.svg', name: 'Union Berlin', strength: 76, nation: 'Alemanha' },
            { image: 'img/alemanha/heiden.svg', name: 'Heidenheim', strength: 75, nation: 'Alemanha' },
            { image: 'img/alemanha/mainz.svg', name: 'Mainz 05', strength: 75, nation: 'Alemanha' },
            { image: 'img/alemanha/ausburg.svg', name: 'Augsburg', strength: 74, nation: 'Alemanha' },
            { image: 'img/alemanha/koln.svg', name: 'Koln', strength: 73, nation: 'Alemanha' },
            { image: 'img/alemanha/schalke.svg', name: 'Schalke 04', strength: 73, nation: 'Alemanha' },
            { image: 'img/alemanha/hertha.svg', name: 'Hertha BSC', strength: 72, nation: 'Alemanha' }
        ]
    },
    espanha: {
        label: 'Liga Espanha',
        teams: [
            { image: 'img/espanha/madrid.svg', name: 'Real Madrid', strength: 95, nation: 'Espanha' },
            { image: 'img/espanha/barca.svg', name: 'Barcelona', strength: 92, nation: 'Espanha' },
            { image: 'img/espanha/atletico.svg', name: 'Atlético de Madrid', strength: 87, nation: 'Espanha' },
            { image: 'img/espanha/sevilla.svg', name: 'Sevilla', strength: 84, nation: 'Espanha' },
            { image: 'img/espanha/valencia.svg', name: 'Valencia', strength: 80, nation: 'Espanha' },
            { image: 'img/espanha/villa.svg', name: 'Villarreal', strength: 82, nation: 'Espanha' },
            { image: 'img/espanha/socieda.svg', name: 'Real Sociedad', strength: 83, nation: 'Espanha' },
            { image: 'img/espanha/bilbao.svg', name: 'Athletic Club Bilbao', strength: 81, nation: 'Espanha' },
            { image: 'img/espanha/girona.svg', name: 'Girona', strength: 84, nation: 'Espanha' },
            { image: 'img/espanha/betis.svg', name: 'Real Betis', strength: 82, nation: 'Espanha' },
            { image: 'img/espanha/osasuna.svg', name: 'Osasuna', strength: 78, nation: 'Espanha' },
            { image: 'img/espanha/celta.svg', name: 'Celta de Vigo', strength: 77, nation: 'Espanha' },
            { image: 'img/espanha/getafe.svg', name: 'Getafe', strength: 77, nation: 'Espanha' },
            { image: 'img/espanha/mallorca.svg', name: 'Mallorca', strength: 76, nation: 'Espanha' },
            { image: 'img/espanha/alaves.svg', name: 'Alavés', strength: 75, nation: 'Espanha' },
            { image: 'img/espanha/vallecano.svg', name: 'Rayo Vallecano', strength: 75, nation: 'Espanha' },
            { image: 'img/espanha/malaga.svg', name: 'Málaga', strength: 74, nation: 'Espanha' },
            { image: 'img/espanha/espanyol.svg', name: 'Espanyol', strength: 74, nation: 'Espanha' },
            { image: 'img/espanha/valladoid.svg', name: 'Real Valladolid', strength: 73, nation: 'Espanha' },
            { image: 'img/espanha/grana.svg', name: 'Granada', strength: 73, nation: 'Espanha' }
        ]
    },
    argentina: {
        label: 'Liga Argentina',
        teams: [
            { image: 'img/argentina/boca.svg', name: 'Boca Juniors', strength: 86, nation: 'Argentina' },
            { image: 'img/argentina/river.svg', name: 'River Plate', strength: 87, nation: 'Argentina' },
            { image: 'img/argentina/racing.svg', name: 'Racing Club', strength: 82, nation: 'Argentina' },
            { image: 'img/argentina/lorenzo.svg', name: 'San Lorenzo', strength: 78, nation: 'Argentina' },
            { image: 'img/argentina/independente.svg', name: 'Independiente', strength: 80, nation: 'Argentina' },
            { image: 'img/argentina/velez.svg', name: 'Vélez Sarsfield', strength: 79, nation: 'Argentina' },
            { image: 'img/argentina/estudiantes_plata.svg', name: 'Estudiantes', strength: 81, nation: 'Argentina' },
            { image: 'img/argentina/talleres.svg', name: 'Talleres', strength: 80, nation: 'Argentina' },
            { image: 'img/argentina/defensa.svg', name: 'Defensa y Justicia', strength: 79, nation: 'Argentina' },
            { image: 'img/argentina/rosario.svg', name: 'Rosario Central', strength: 78, nation: 'Argentina' },
            { image: 'img/argentina/argentinos.svg', name: 'Argentinos Juniors', strength: 78, nation: 'Argentina' },
            { image: 'img/argentina/lanus.svg', name: 'Lanús', strength: 77, nation: 'Argentina' },
            { image: 'img/argentina/oldboys.svg', name: 'Newell\'s Old Boys', strength: 77, nation: 'Argentina' },
            { image: 'img/argentina/godoy.svg', name: 'Godoy Cruz', strength: 77, nation: 'Argentina' },
            { image: 'img/argentina/huracan.svg', name: 'Huracán', strength: 76, nation: 'Argentina' },
            { image: 'img/argentina/belgrano.svg', name: 'Belgrano', strength: 76, nation: 'Argentina' },
            { image: 'img/argentina/banfield.svg', name: 'Banfield', strength: 75, nation: 'Argentina' },
            { image: 'img/argentina/mendonza.svg', name: 'Gimnasia (LP)', strength: 75, nation: 'Argentina' },
            { image: 'img/argentina/union.svg', name: 'Unión', strength: 74, nation: 'Argentina' },
            { image: 'img/argentina/tigre.svg', name: 'Tigre', strength: 74, nation: 'Argentina' },
            { image: 'img/argentina/cordoba.svg', name: 'Instituto', strength: 74, nation: 'Argentina' },
            { image: 'img/argentina/tucuman.svg', name: 'Atlético Tucumán', strength: 73, nation: 'Argentina' },
            { image: 'img/argentina/platense.svg', name: 'Platense', strength: 73, nation: 'Argentina' },
            { image: 'img/argentina/central_cordoba.svg', name: 'Central Córdoba', strength: 72, nation: 'Argentina' },
            { image: 'img/argentina/sarmiento.svg', name: 'Sarmiento', strength: 71, nation: 'Argentina' },
            { image: 'img/argentina/barracas.svg', name: 'Barracas Central', strength: 71, nation: 'Argentina' },
            { image: 'img/argentina/rivadavia.svg', name: 'Independiente Rivadavia', strength: 70, nation: 'Argentina' },
            { image: 'img/argentina/deportivo_riestra.svg', name: 'Deportivo Riestra', strength: 69, nation: 'Argentina' },
            { image: 'img/argentina/laplata.svg', name: 'Club de Gimnasia y Esgrima La Platav', strength: 69, nation: 'Argentina' },
            { image: 'img/argentina/aldosivi.svg', name: 'Aldosivi', strength: 71, nation: 'Argentina' }
        ]
    },
    usa: {
        label: 'Liga USA',
        teams: [
            { image: 'img/usa/galaxy.svg', name: 'LA Galaxy', strength: 78, nation: 'Estados Unidos' },
            { image: 'img/usa/angeles.svg', name: 'LAFC', strength: 80, nation: 'Estados Unidos' },
            { image: 'img/usa/york.svg', name: 'NYCFC', strength: 79, nation: 'Estados Unidos' },
            { image: 'img/usa/intermiami.svg', name: 'Inter Miami', strength: 78, nation: 'Estados Unidos' },
            { image: 'img/usa/seattle.svg', name: 'Seattle Sounders', strength: 80, nation: 'Estados Unidos' },
            { image: 'img/usa/atlanta.svg', name: 'Atlanta United', strength: 77, nation: 'Estados Unidos' },
            { image: 'img/usa/dallas.svg', name: 'FC Dallas', strength: 76, nation: 'Estados Unidos' },
            { image: 'img/usa/filadelfia.svg', name: 'Philadelphia Union', strength: 75, nation: 'Estados Unidos' },
            { image: 'img/usa/columbus.svg', name: 'Columbus Crew', strength: 81, nation: 'Estados Unidos' },
            { image: 'img/usa/cincinnati.svg', name: 'FC Cincinnati', strength: 80, nation: 'Estados Unidos' },
            { image: 'img/usa/redbull.svg', name: 'New York Red Bulls', strength: 76, nation: 'Estados Unidos' },
            { image: 'img/usa/orlando.svg', name: 'Orlando City', strength: 77, nation: 'Estados Unidos' },
            { image: 'img/usa/realsalt.svg', name: 'Real Salt Lake', strength: 77, nation: 'Estados Unidos' },
            { image: 'img/usa/dynamo.svg', name: 'Houston Dynamo', strength: 76, nation: 'Estados Unidos' },
            { image: 'img/usa/timbers.svg', name: 'Portland Timbers', strength: 76, nation: 'Estados Unidos' },
            { image: 'img/usa/louis.svg', name: 'St. Louis City SC', strength: 76, nation: 'Estados Unidos' },
            { image: 'img/usa/england.svg', name: 'New England Revolution', strength: 75, nation: 'Estados Unidos' },
            { image: 'img/usa/minnesotta.svg', name: 'Minnesota United', strength: 75, nation: 'Estados Unidos' },
            { image: 'img/usa/charlotte.svg', name: 'Charlotte FC', strength: 75, nation: 'Estados Unidos' },
            { image: 'img/usa/nashville.svg', name: 'Nashville SC', strength: 75, nation: 'Estados Unidos' },
            { image: 'img/usa/vancouver.svg', name: 'Vancouver Whitecaps', strength: 75, nation: 'Canadá' },
            { image: 'img/usa/austin.svg', name: 'Austin FC', strength: 74, nation: 'Estados Unidos' },
            { image: 'img/usa/colorado.svg', name: 'Colorado Rapids', strength: 74, nation: 'Estados Unidos' },
            { image: 'img/usa/kansas.svg', name: 'Sporting Kansas City', strength: 74, nation: 'Estados Unidos' },
            { image: 'img/usa/toronto.svg', name: 'Toronto FC', strength: 74, nation: 'Canadá' },
            { image: 'img/usa/united.svg', name: 'D.C. United', strength: 73, nation: 'Estados Unidos' },
            { image: 'img/usa/montreal.svg', name: 'CF Montréal', strength: 73, nation: 'Canadá' },
            { image: 'img/usa/jose.svg', name: 'San Jose Earthquakes', strength: 72, nation: 'Estados Unidos' },
            { image: 'img/usa/chicagofire.svg', name: 'Chicago Fire', strength: 72, nation: 'Estados Unidos' },
            { image: 'img/usa/diego.svg', name: 'San Diego FC', strength: 72, nation: 'Estados Unidos' }
        ]
    },
    japao: {
        label: 'Liga Japão',
        teams: [
            { image: 'img/japao/frontale.svg', name: 'Kawasaki Frontale', strength: 78, nation: 'Japão' },
            { image: 'img/japao/marinos.svg', name: 'Yokohama F. Marinos', strength: 79, nation: 'Japão' },
            { image: 'img/japao/reds.svg', name: 'Urawa Reds', strength: 77, nation: 'Japão' },
            { image: 'img/japao/antlers.svg', name: 'Kashima Antlers', strength: 76, nation: 'Japão' },
            { image: 'img/japao/gamba.svg', name: 'Gamba Osaka', strength: 75, nation: 'Japão' },
            { image: 'img/japao/fctokyo.svg', name: 'FC Tokyo', strength: 74, nation: 'Japão' },
            { image: 'img/japao/cerezo.svg', name: 'Cerezo Osaka', strength: 74, nation: 'Japão' },
            { image: 'img/japao/nagoya.svg', name: 'Nagoya Grampus', strength: 75, nation: 'Japão' },
            { image: 'img/japao/kobe.svg', name: 'Vissel Kobe', strength: 79, nation: 'Japão' },
            { image: 'img/japao/sanfrecce.svg', name: 'Sanfrecce Hiroshima', strength: 78, nation: 'Japão' },
            { image: 'img/japao/machida.svg', name: 'Machida Zelvia', strength: 77, nation: 'Japão' },
            { image: 'img/japao/fukuoka.svg', name: 'Avispa Fukuoka', strength: 74, nation: 'Japão' },
            { image: 'img/japao/reysol.svg', name: 'Kashiwa Reysol', strength: 73, nation: 'Japão' },
            { image: 'img/japao/sapporo.svg', name: 'Consadole Sapporo', strength: 73, nation: 'Japão' },
            { image: 'img/japao/albirex.svg', name: 'Albirex Niigata', strength: 73, nation: 'Japão' },
            { image: 'img/japao/kyoto.svg', name: 'Kyoto Sanga', strength: 72, nation: 'Japão' },
            { image: 'img/japao/jubilo.svg', name: 'Jubilo Iwata', strength: 72, nation: 'Japão' },
            { image: 'img/japao/sagan.svg', name: 'Sagan Tosu', strength: 71, nation: 'Japão' },
            { image: 'img/japao/bellmare.svg', name: 'Shonan Bellmare', strength: 71, nation: 'Japão' },
            { image: 'img/japao/verdy.svg', name: 'Tokyo Verdy', strength: 70, nation: 'Japão' }
        ]
    },
    belgica_a: {
        label: 'Liga Bélgica',
        teams: [
            { image: 'img/belgica/club.svg', name: 'Club Brugge', strength: 80, nation: 'Bélgica' },
            { image: 'img/belgica/ander.svg', name: 'Anderlecht', strength: 78, nation: 'Bélgica' },
            { image: 'img/belgica/genk.svg', name: 'Genk', strength: 77, nation: 'Bélgica' },
            { image: 'img/belgica/gent.svg', name: 'Gent', strength: 76, nation: 'Bélgica' },
            { image: 'img/belgica/liege.svg', name: 'Standard de Liège', strength: 74, nation: 'Bélgica' },
            { image: 'img/belgica/antwerp.svg', name: 'Antwerp', strength: 75, nation: 'Bélgica' },
            { image: 'img/belgica/brugge.svg', name: 'Brugge KV', strength: 73, nation: 'Bélgica' },
            { image: 'img/belgica/mechelen.svg', name: 'Mechelen', strength: 72, nation: 'Bélgica' },
            { image: 'img/belgica/gilloise.svg', name: 'Union Saint-Gilloise', strength: 79, nation: 'Bélgica' },
            { image: 'img/belgica/charleroi.svg', name: 'Charleroi', strength: 72, nation: 'Bélgica' },
            { image: 'img/belgica/truidense.svg', name: 'Sint-Truiden', strength: 71, nation: 'Bélgica' },
            { image: 'img/belgica/wester.svg', name: 'Westerlo', strength: 71, nation: 'Bélgica' },
            { image: 'img/belgica/leuven.svg', name: 'OH Leuven', strength: 70, nation: 'Bélgica' },
            { image: 'img/belgica/kort.svg', name: 'Kortrijk', strength: 69, nation: 'Bélgica' },
            { image: 'img/belgica/dender.svg', name: 'Dender', strength: 68, nation: 'Bélgica' },
            { image: 'img/belgica/zulte.svg', name: 'Zulte Waregem', strength: 68, nation: 'Bélgica' }
        ]
    },
    holanda: {
        label: 'Liga Holanda',
        teams: [
            { image: 'img/holanda/ajax.svg', name: 'Ajax', strength: 84, nation: 'Holanda' },
            { image: 'img/holanda/psv.svg', name: 'PSV', strength: 82, nation: 'Holanda' },
            { image: 'img/holanda/feye.svg', name: 'Feyenoord', strength: 81, nation: 'Holanda' },
            { image: 'img/holanda/alkmaar.svg', name: 'AZ Alkmaar', strength: 78, nation: 'Holanda' },
            { image: 'img/holanda/alkmaar.svg', name: 'Excelsior', strength: 78, nation: 'Holanda' },
            { image: 'img/holanda/twente.svg', name: 'Twente', strength: 76, nation: 'Holanda' },
            { image: 'img/holanda/utrechet.svg', name: 'Utrecht', strength: 75, nation: 'Holanda' },
            { image: 'img/holanda/heerenveen.svg', name: 'Heerenveen', strength: 73, nation: 'Holanda' },
            { image: 'img/holanda/den.svg', name: 'ADO Den Haag', strength: 74, nation: 'Holanda' },
            { image: 'img/holanda/nec.svg', name: 'NEC Nijmegen', strength: 74, nation: 'Holanda' },
            { image: 'img/holanda/sparta.svg', name: 'Sparta Rotterdam', strength: 73, nation: 'Holanda' },
            { image: 'img/holanda/ahead.svg', name: 'Go Ahead Eagles', strength: 72, nation: 'Holanda' },
            { image: 'img/holanda/gronin.svg', name: 'FC Groningen', strength: 72, nation: 'Holanda' },
            { image: 'img/holanda/fortuna.svg', name: 'Fortuna Sittard', strength: 71, nation: 'Holanda' },
            { image: 'img/holanda/zwolle.svg', name: 'PEC Zwolle', strength: 71, nation: 'Holanda' },
            { image: 'img/holanda/telstar.svg', name: 'Telstar', strength: 70, nation: 'Holanda' },
            { image: 'img/holanda/willem.svg', name: 'Willem II', strength: 70, nation: 'Holanda' },
            { image: 'img/holanda/sparta.svg', name: 'Sparta Rotterdam', strength: 69, nation: 'Holanda' },
            { image: 'img/holanda/cambuur.svg', name: 'SC Cambuur', strength: 69, nation: 'Holanda' }
        ]
    },
    noruega: {
        label: 'Liga Noruega',
        teams: [
            { image: 'img/noruega/rosen.svg', name: 'Rosenborg', strength: 76, nation: 'Noruega' },
            { image: 'img/noruega/molde.svg', name: 'Molde', strength: 77, nation: 'Noruega' },
            { image: 'img/noruega/bodo.svg', name: 'Bodø/Glimt', strength: 78, nation: 'Noruega' },
            { image: 'img/noruega/viking.svg', name: 'Viking', strength: 74, nation: 'Noruega' },
            { image: 'img/noruega/brann.svg', name: 'Brann', strength: 73, nation: 'Noruega' },
            { image: 'img/noruega/lille.svg', name: 'Lillestrøm', strength: 72, nation: 'Noruega' },
            { image: 'img/noruega/sarps.svg', name: 'Sarpsborg', strength: 71, nation: 'Noruega' },
            { image: 'img/noruega/tromso.svg', name: 'Tromsø', strength: 70, nation: 'Noruega' },
            { image: 'img/noruega/strom.svg', name: 'Strømsgodset', strength: 71, nation: 'Noruega' },
            { image: 'img/noruega/odds.svg', name: 'Odds BK', strength: 70, nation: 'Noruega' },
            { image: 'img/noruega/fred.svg', name: 'Fredrikstad', strength: 70, nation: 'Noruega' },
            { image: 'img/noruega/aale.svg', name: 'Aalesund', strength: 69, nation: 'Noruega' },
            { image: 'img/noruega/hamkam.svg', name: 'HamKam', strength: 68, nation: 'Noruega' },
            { image: 'img/noruega/sande.svg', name: 'Sandefjord', strength: 67, nation: 'Noruega' },
            { image: 'img/noruega/kris.svg', name: 'Kristiansund', strength: 67, nation: 'Noruega' },
            { image: 'img/noruega/kfum.svg', name: 'KFUM Oslo', strength: 66, nation: 'Noruega' }
        ]
    },
    portugal: {
        label: 'Liga Portugal',
        teams: [
            { image: 'img/portugal/porto.svg', name: 'Porto', strength: 87, nation: 'Portugal' },
            { image: 'img/portugal/benfica.svg', name: 'Benfica', strength: 88, nation: 'Portugal' },
            { image: 'img/portugal/sport.svg', name: 'Sporting', strength: 86, nation: 'Portugal' },
            { image: 'img/portugal/braga.svg', name: 'Braga', strength: 82, nation: 'Portugal' },
            { image: 'img/portugal/alverca.svg', name: 'Alverca', strength: 79, nation: 'Portugal' },
            { image: 'img/portugal/fama.svg', name: 'Famalicão', strength: 76, nation: 'Portugal' },
            { image: 'img/portugal/boa.svg', name: 'Boavista', strength: 75, nation: 'Portugal' },
            { image: 'img/portugal/vitoria.svg', name: 'Vitória SC', strength: 74, nation: 'Portugal' },
            { image: 'img/portugal/ave.svg', name: 'Rio Ave', strength: 75, nation: 'Portugal' },
            { image: 'img/portugal/arouca.svg', name: 'Arouca', strength: 75, nation: 'Portugal' },
            { image: 'img/portugal/casa.svg', name: 'Casa Pia', strength: 74, nation: 'Portugal' },
            { image: 'img/portugal/gil.svg', name: 'Gil Vicente', strength: 73, nation: 'Portugal' },
            { image: 'img/portugal/praia.svg', name: 'Estoril Praia', strength: 73, nation: 'Portugal' },
            { image: 'img/portugal/far.svg', name: 'Farense', strength: 72, nation: 'Portugal' },
            { image: 'img/portugal/amadora.svg', name: 'Estrela da Amadora', strength: 72, nation: 'Portugal' },
            { image: 'img/portugal/morei.svg', name: 'Moreirense', strength: 74, nation: 'Portugal' },
            { image: 'img/portugal/madeira.svg', name: 'Nacional', strength: 71, nation: 'Portugal' },
            { image: 'img/portugal/santa.svg', name: 'Santa Clara', strength: 72, nation: 'Portugal' }
        ]
    },
    suecia: {
        label: 'Liga Suécia',
        teams: [
            { image: 'img/suecia/malmo.svg', name: 'Malmö FF', strength: 76, nation: 'Suécia' },
            { image: 'img/suecia/djur.svg', name: 'Djurgårdens IF', strength: 74, nation: 'Suécia' },
            { image: 'img/suecia/hack.svg', name: 'BK Häcken', strength: 74, nation: 'Suécia' },
            { image: 'img/suecia/elfs.svg', name: 'IF Elfsborg', strength: 73, nation: 'Suécia' },
            { image: 'img/suecia/hamma.svg', name: 'Hammarby IF', strength: 72, nation: 'Suécia' },
            { image: 'img/suecia/aik.svg', name: 'AIK', strength: 72, nation: 'Suécia' },
            { image: 'img/suecia/ifk.svg', name: 'IFK Göteborg', strength: 71, nation: 'Suécia' },
            { image: 'img/suecia/norrk.svg', name: 'IFK Norrköping', strength: 70, nation: 'Suécia' },
            { image: 'img/suecia/deger.svg', name: 'Degerfors IF', strength: 69, nation: 'Suécia' },
            { image: 'img/suecia/sirius.svg', name: 'Sirius', strength: 69, nation: 'Suécia' },
            { image: 'img/suecia/mjal.svg', name: 'Mjällby AIF', strength: 69, nation: 'Suécia' },
            { image: 'img/suecia/halm.svg', name: 'Halmstads BK', strength: 68, nation: 'Suécia' },
            { image: 'img/suecia/varnamo.svg', name: 'IFK Värnamo', strength: 68, nation: 'Suécia' },
            { image: 'img/suecia/gais.svg', name: 'GAIS', strength: 68, nation: 'Suécia' },
            { image: 'img/suecia/brom.svg', name: 'Brommapojkarna', strength: 67, nation: 'Suécia' },
            { image: 'img/suecia/osters.svg', name: 'Osters IF', strength: 67, nation: 'Suécia' }
        ]
    },
    mexico: {
        label: 'Liga México',
        teams: [
            { image: 'img/mexico/america.svg', name: 'América', strength: 85, nation: 'México' },
            { image: 'img/mexico/guada.svg', name: 'Chivas', strength: 84, nation: 'México' },
            { image: 'img/mexico/cruz.svg', name: 'Cruz Azul', strength: 82, nation: 'México' },
            { image: 'img/mexico/pumas.svg', name: 'Pumas', strength: 81, nation: 'México' },
            { image: 'img/mexico/monte.svg', name: 'Monterrey', strength: 83, nation: 'México' },
            { image: 'img/mexico/tigres.svg', name: 'Tigres', strength: 83, nation: 'México' },
            { image: 'img/mexico/santos.svg', name: 'Santos Laguna', strength: 80, nation: 'México' },
            { image: 'img/mexico/atlas.svg', name: 'Atlas', strength: 79, nation: 'México' },
            { image: 'img/mexico/toluca.svg', name: 'Toluca', strength: 80, nation: 'México' },
            { image: 'img/mexico/pachuca.svg', name: 'Pachuca', strength: 80, nation: 'México' },
            { image: 'img/mexico/leon.svg', name: 'León', strength: 79, nation: 'México' },
            { image: 'img/mexico/queretaro.svg', name: 'Querétaro', strength: 77, nation: 'México' },
            { image: 'img/mexico/sanluis.svg', name: 'Atlético San Luis', strength: 77, nation: 'México' },
            { image: 'img/mexico/necaxa.svg', name: 'Necaxa', strength: 76, nation: 'México' },
            { image: 'img/mexico/tijuana.svg', name: 'Tijuana', strength: 76, nation: 'México' },
            { image: 'img/mexico/puebla.svg', name: 'Puebla', strength: 75, nation: 'México' },
            { image: 'img/mexico/maza.svg', name: 'Mazatlán', strength: 74, nation: 'México' },
            { image: 'img/mexico/juarez.svg', name: 'Juárez', strength: 74, nation: 'México' }
        ]
    },
    venezuela: {
        label: 'Liga Venezuela',
        teams: [
            { image: 'img/venezuela/caracas.svg', name: 'Caracas', strength: 72, nation: 'Venezuela' },
            { image: 'img/venezuela/tachira.svg', name: 'Deportivo Táchira', strength: 73, nation: 'Venezuela' },
            { image: 'img/venezuela/zamora.svg', name: 'Zamora', strength: 71, nation: 'Venezuela' },
            { image: 'img/venezuela/monagas.svg', name: 'Monagas', strength: 70, nation: 'Venezuela' },
            { image: 'img/venezuela/portuguesa.svg', name: 'Portuguesa', strength: 69, nation: 'Venezuela' },
            { image: 'img/venezuela/estudiantes.svg', name: 'Estudiantes de Mérida', strength: 68, nation: 'Venezuela' },
            { image: 'img/venezuela/guaira.svg', name: 'La Guaira', strength: 68, nation: 'Venezuela' },
            { image: 'img/venezuela/truji.png', name: 'Trujillanos', strength: 67, nation: 'Venezuela' },
            { image: 'img/venezuela/cara.svg', name: 'Carabobo FC', strength: 70, nation: 'Venezuela' },
            { image: 'img/venezuela/metro.svg', name: 'Metropolitanos', strength: 70, nation: 'Venezuela' },
            { image: 'img/venezuela/puerto.svg', name: 'Academia Puerto Cabello', strength: 69, nation: 'Venezuela' },
            { image: 'img/venezuela/anzo.svg', name: 'Anzoátegui', strength: 67, nation: 'Venezuela' },
            { image: 'img/venezuela/inter.png', name: 'Inter de Barinas', strength: 66, nation: 'Venezuela' },
            { image: 'img/venezuela/rayo.svg', name: 'Rayo Zuliano', strength: 66, nation: 'Venezuela' },
            { image: 'img/venezuela/uni.svg', name: 'Universidad Central', strength: 65, nation: 'Venezuela' },
            { image: 'img/venezuela/yara.svg', name: 'Yaracuyanos FC', strength: 65, nation: 'Venezuela' }
        ]
    },
    suica: {
        label: 'Liga Suíça',
        teams: [
            { image: 'img/suica/boys.svg', name: 'Young Boys', strength: 80, nation: 'Suíça' },
            { image: 'img/suica/basel.svg', name: 'Basel', strength: 79, nation: 'Suíça' },
            { image: 'img/suica/zurich.svg', name: 'Zurique', strength: 77, nation: 'Suíça' },
            { image: 'img/suica/lugano.svg', name: 'Lugano', strength: 76, nation: 'Suíça' },
            { image: 'img/suica/gallen.svg', name: 'St. Gallen', strength: 75, nation: 'Suíça' },
            { image: 'img/suica/serve.svg', name: 'Servette', strength: 74, nation: 'Suíça' },
            { image: 'img/suica/luzern.svg', name: 'Luzern', strength: 74, nation: 'Suíça' },
            { image: 'img/suica/sion.svg', name: 'Sion', strength: 73, nation: 'Suíça' },
            { image: 'img/suica/grass.svg', name: 'Grasshopper', strength: 72, nation: 'Suíça' },
            { image: 'img/suica/winter.svg', name: 'Winterthur', strength: 71, nation: 'Suíça' },
            { image: 'img/suica/lau.svg', name: 'Lausanne-Sport', strength: 71, nation: 'Suíça' },
            { image: 'img/suica/thun.svg', name: 'FC Thun', strength: 70, nation: 'Suíça' }
        ]
    },
    turquia: {
        label: 'Liga Turquia',
        teams: [
            { image: 'img/turquia/galata.svg', name: 'Galatasaray', strength: 83, nation: 'Turquia' },
            { image: 'img/turquia/fener.svg', name: 'Fenerbahçe', strength: 82, nation: 'Turquia' },
            { image: 'img/turquia/besiktas.svg', name: 'Besiktas', strength: 82, nation: 'Turquia' },
            { image: 'img/turquia/trab.svg', name: 'Trabzonspor', strength: 80, nation: 'Turquia' },
            { image: 'img/turquia/basak.svg', name: 'Istanbul Basaksehir', strength: 78, nation: 'Turquia' },
            { image: 'img/turquia/siva.svg', name: 'Sivasspor', strength: 76, nation: 'Turquia' },
            { image: 'img/turquia/alany.svg', name: 'Alanyaspor', strength: 75, nation: 'Turquia' },
            { image: 'img/turquia/cay.svg', name: 'Rizespor', strength: 74, nation: 'Turquia' },
            { image: 'img/turquia/kasim.svg', name: 'Kasimpasa', strength: 74, nation: 'Turquia' },
            { image: 'img/turquia/antaly.svg', name: 'Antalyaspor', strength: 73, nation: 'Turquia' },
            { image: 'img/turquia/gazian.svg', name: 'Gaziantep FK', strength: 73, nation: 'Turquia' },
            { image: 'img/turquia/adana.svg', name: 'Adana Demirspor', strength: 73, nation: 'Turquia' },
            { image: 'img/turquia/samsun.svg', name: 'Samsunspor', strength: 72, nation: 'Turquia' },
            { image: 'img/turquia/kay.svg', name: 'Kayserispor', strength: 72, nation: 'Turquia' },
            { image: 'img/turquia/konya.svg', name: 'Konyaspor', strength: 71, nation: 'Turquia' },
            { image: 'img/turquia/pendik.svg', name: 'Pendikspor', strength: 71, nation: 'Turquia' },
            { image: 'img/turquia/hatay.svg', name: 'Hatayspor', strength: 70, nation: 'Turquia' },
            { image: 'img/turquia/eyu.svg', name: 'Eyüpspor', strength: 70, nation: 'Turquia' },
            { image: 'img/turquia/istan.svg', name: 'İstanbulspor', strength: 69, nation: 'Turquia' },
            { image: 'img/turquia/goz.svg', name: 'Göztepe', strength: 69, nation: 'Turquia' }
        ]
    },
    tcheca: {
        label: 'Liga Tcheca',
        teams: [
            { image: 'img/tcheca/slavia.svg', name: 'Slavia Praga', strength: 82, nation: 'República Tcheca' },
            { image: 'img/tcheca/sparta.svg', name: 'Sparta Praga', strength: 81, nation: 'República Tcheca' },
            { image: 'img/tcheca/viktoria.svg', name: 'Viktoria Plzeň', strength: 79, nation: 'República Tcheca' },
            { image: 'img/tcheca/banik.svg', name: 'Baník Ostrava', strength: 76, nation: 'República Tcheca' },
            { image: 'img/tcheca/sigma.svg', name: 'Sigma Olomouc', strength: 74, nation: 'República Tcheca' },
            { image: 'img/tcheca/slovan.svg', name: 'Slovan Liberec', strength: 73, nation: 'República Tcheca' },
            { image: 'img/tcheca/jablo.png', name: 'Jablonec', strength: 72, nation: 'República Tcheca' },
            { image: 'img/tcheca/bohe.svg', name: 'Bohemians 1905', strength: 71, nation: 'República Tcheca' },
            { image: 'img/tcheca/mlada.svg', name: 'Mladá Boleslav', strength: 71, nation: 'República Tcheca' },
            { image: 'img/tcheca/slovacko.svg', name: 'Slovácko', strength: 70, nation: 'República Tcheca' },
            { image: 'img/tcheca/teplice.svg', name: 'Teplice', strength: 69, nation: 'República Tcheca' },
            { image: 'img/tcheca/hradec.png', name: 'Hradec Králové', strength: 69, nation: 'República Tcheca' },
            { image: 'img/tcheca/zlin.png', name: 'FC Zlin', strength: 68, nation: 'República Tcheca' },
            { image: 'img/tcheca/pardubice.svg', name: 'Pardubice', strength: 68, nation: 'República Tcheca' },
            { image: 'img/tcheca/karvina.svg', name: 'Karviná', strength: 67, nation: 'República Tcheca' },
            { image: 'img/tcheca/dukla.svg', name: 'Dukla Praga', strength: 67, nation: 'República Tcheca' }
        ]
    },
    grecia: {
        label: 'Liga Grécia',
        teams: [
            { image: 'img/grecia/olympiacos.svg', name: 'Olympiacos', strength: 82, nation: 'Grécia' },
            { image: 'img/grecia/paok.svg', name: 'PAOK', strength: 81, nation: 'Grécia' },
            { image: 'img/grecia/pana.svg', name: 'Panathinaikos', strength: 80, nation: 'Grécia' },
            { image: 'img/grecia/athens.svg', name: 'AEK Atenas', strength: 80, nation: 'Grécia' },
            { image: 'img/grecia/aris.svg', name: 'Aris', strength: 76, nation: 'Grécia' },
            { image: 'img/grecia/crete.svg', name: 'OFI Crete', strength: 73, nation: 'Grécia' },
            { image: 'img/grecia/atromitos.svg', name: 'Atromitos', strength: 72, nation: 'Grécia' },
            { image: 'img/grecia/asteras.svg', name: 'Asteras Tripolis', strength: 72, nation: 'Grécia' },
            { image: 'img/grecia/paneto.svg', name: 'Panetolikos', strength: 71, nation: 'Grécia' },
            { image: 'img/grecia/kifisia.svg', name: 'A.E Kifisia', strength: 70, nation: 'Grécia' },
            { image: 'img/grecia/volos.svg', name: 'Volos NFC', strength: 70, nation: 'Grécia' },
            { image: 'img/grecia/panserra.svg', name: 'Panserraikos', strength: 69, nation: 'Grécia' },
            { image: 'img/grecia/pas.svg', name: 'PAS Giannina', strength: 68, nation: 'Grécia' },
            { image: 'img/grecia/levadiakos.svg', name: 'Levadiakos', strength: 68, nation: 'Grécia' }
        ]
    },
    escocia: {
        label: 'Liga Escócia',
        teams: [
            { image: 'img/escocia/celtic.svg', name: 'Celtic', strength: 83, nation: 'Escócia' },
            { image: 'img/escocia/rangers.svg', name: 'Rangers', strength: 82, nation: 'Escócia' },
            { image: 'img/escocia/aber.svg', name: 'Aberdeen', strength: 76, nation: 'Escócia' },
            { image: 'img/escocia/heart.svg', name: 'Hearts', strength: 74, nation: 'Escócia' },
            { image: 'img/escocia/hiber.svg', name: 'Hibernian', strength: 73, nation: 'Escócia' },
            { image: 'img/escocia/mother.svg', name: 'Motherwell', strength: 72, nation: 'Escócia' },
            { image: 'img/escocia/kil.svg', name: 'Kilmarnock', strength: 71, nation: 'Escócia' },
            { image: 'img/escocia/st.svg', name: 'St. Johnstone', strength: 70, nation: 'Escócia' },
            { image: 'img/escocia/dundee.svg', name: 'Dundee FC', strength: 70, nation: 'Escócia' },
            { image: 'img/escocia/st.svg', name: 'St. Mirren', strength: 69, nation: 'Escócia' },
            { image: 'img/escocia/livi.svg', name: 'Livingston FC', strength: 68, nation: 'Escócia' },
            { image: 'img/escocia/united.svg', name: 'Dundee United', strength: 68, nation: 'Escócia' }
        ]
    },
    russia: {
        label: 'Liga Rússia',
        teams: [
            { image: 'img/russia/zenit.svg', name: 'Zenit', strength: 83, nation: 'Rússia' },
            { image: 'img/russia/spar.svg', name: 'Spartak Moscou', strength: 80, nation: 'Rússia' },
            { image: 'img/russia/cska.svg', name: 'CSKA Moscou', strength: 79, nation: 'Rússia' },
            { image: 'img/russia/loko.svg', name: 'Lokomotiv Moscou', strength: 79, nation: 'Rússia' },
            { image: 'img/russia/moscoy.svg', name: 'Dynamo Moscou', strength: 78, nation: 'Rússia' },
            { image: 'img/russia/kras.svg', name: 'FC Krasnodar', strength: 78, nation: 'Rússia' },
            { image: 'img/russia/rostov.svg', name: 'FC Rostov', strength: 76, nation: 'Rússia' },
            { image: 'img/russia/ak.svg', name: 'Akhmat Grozny', strength: 75, nation: 'Rússia' },
            { image: 'img/russia/kry.svg', name: 'Krylia Sovetov', strength: 74, nation: 'Rússia' },
            { image: 'img/russia/rubin.svg', name: 'Rubin Kazan', strength: 74, nation: 'Rússia' },
            { image: 'img/russia/oren.svg', name: 'Orenburg', strength: 73, nation: 'Rússia' },
            { image: 'img/russia/pari.svg', name: 'Pari NN', strength: 72, nation: 'Rússia' },
            { image: 'img/russia/akron.svg', name: 'Akron Togliatti', strength: 71, nation: 'Rússia' },
            { image: 'img/russia/baltika.svg', name: 'Baltika', strength: 70, nation: 'Rússia' },
            { image: 'img/russia/sochi.svg', name: 'Sochi', strength: 70, nation: 'Rússia' },
            { image: 'img/russia/mak.svg', name: 'Dynamo Makhachkala', strength: 69, nation: 'Rússia' }
        ]
    },
    arabia: {
        label: 'Liga Arábia',
        teams: [
            { name: 'Al Hilal', strength: 84, nation: 'Arábia Saudita' },
            { name: 'Al Nassr', strength: 83, nation: 'Arábia Saudita' },
            { name: 'Al Ittihad', strength: 82, nation: 'Arábia Saudita' },
            { name: 'Al Ahli', strength: 81, nation: 'Arábia Saudita' },
            { name: 'Al Shabab', strength: 78, nation: 'Arábia Saudita' },
            { name: 'Al Ettifaq', strength: 77, nation: 'Arábia Saudita' },
            { name: 'Al Taawoun', strength: 76, nation: 'Arábia Saudita' },
            { name: 'Al Fateh', strength: 75, nation: 'Arábia Saudita' },
            { name: 'Al Khaleej', strength: 73, nation: 'Arábia Saudita' },
            { name: 'Al Fayha', strength: 73, nation: 'Arábia Saudita' },
            { name: 'Al Raed', strength: 72, nation: 'Arábia Saudita' },
            { name: 'Al Okhdood', strength: 72, nation: 'Arábia Saudita' },
            { name: 'Al Wehda', strength: 71, nation: 'Arábia Saudita' },
            { name: 'Damac FC', strength: 71, nation: 'Arábia Saudita' },
            { name: 'Al Riyadh', strength: 70, nation: 'Arábia Saudita' },
            { name: 'Al Qadsiah', strength: 70, nation: 'Arábia Saudita' },
            { name: 'Al Kholood', strength: 69, nation: 'Arábia Saudita' },
            { name: 'Al Orobah', strength: 68, nation: 'Arábia Saudita' }
        ]
    },
    coreia: {
        label: 'Liga Coreia',
        teams: [
            { name: 'Jeonbuk Hyundai', strength: 79, nation: 'Coreia do Sul' },
            { name: 'Ulsan', strength: 78, nation: 'Coreia do Sul' },
            { name: 'Pohang', strength: 77, nation: 'Coreia do Sul' },
            { name: 'FC Seoul', strength: 76, nation: 'Coreia do Sul' },
            { name: 'Suwon Bluewings', strength: 75, nation: 'Coreia do Sul' },
            { name: 'Daegu', strength: 74, nation: 'Coreia do Sul' },
            { name: 'Incheon', strength: 72, nation: 'Coreia do Sul' },
            { name: 'Gwangju', strength: 70, nation: 'Coreia do Sul' },
            { name: 'Jeju United', strength: 71, nation: 'Coreia do Sul' },
            { name: 'Daejeon Hana Citizen', strength: 70, nation: 'Coreia do Sul' },
            { name: 'Gangwon', strength: 69, nation: 'Coreia do Sul' },
            { name: 'Suwon FC', strength: 68, nation: 'Coreia do Sul' }
        ]
    },
    bolivia: {
        label: 'Liga Bolívia',
        teams: [
            { name: 'Bolívar', strength: 76, nation: 'Bolívia' },
            { name: 'The Strongest', strength: 75, nation: 'Bolívia' },
            { name: 'Jorge Wilstermann', strength: 74, nation: 'Bolívia' },
            { name: 'Oriente Petrolero', strength: 72, nation: 'Bolívia' },
            { name: 'Blooming', strength: 71, nation: 'Bolívia' },
            { name: 'Guabirá', strength: 70, nation: 'Bolívia' },
            { name: 'Royal Pari', strength: 69, nation: 'Bolívia' },
            { name: 'Nacional Potosí', strength: 68, nation: 'Bolívia' },
            { name: 'Always Ready', strength: 72, nation: 'Bolívia' },
            { name: 'Aurora', strength: 71, nation: 'Bolívia' },
            { name: 'Real Tomayapo', strength: 69, nation: 'Bolívia' },
            { name: 'Independiente Petrolero', strength: 68, nation: 'Bolívia' },
            { name: 'Real Santa Cruz', strength: 67, nation: 'Bolívia' },
            { name: 'San Antonio Bulo Bulo', strength: 67, nation: 'Bolívia' },
            { name: 'GV San José', strength: 66, nation: 'Bolívia' },
            { name: 'Universitario de Vinto', strength: 66, nation: 'Bolívia' }
        ]
    },
    chile: {
        label: 'Liga Chile',
        teams: [
            { name: 'Colo-Colo', strength: 78, nation: 'Chile' },
            { name: 'Universidad de Chile', strength: 77, nation: 'Chile' },
            { name: 'Universidad Catolica', strength: 76, nation: 'Chile' },
            { name: 'Cobreloa', strength: 72, nation: 'Chile' },
            { name: 'Palestino', strength: 71, nation: 'Chile' },
            { name: "O'Higgins", strength: 70, nation: 'Chile' },
            { name: 'Everton', strength: 70, nation: 'Chile' },
            { name: 'Audax Italiano', strength: 69, nation: 'Chile' },
            { name: 'Huachipato', strength: 72, nation: 'Chile' },
            { name: 'Coquimbo Unido', strength: 71, nation: 'Chile' },
            { name: 'Unión Española', strength: 70, nation: 'Chile' },
            { name: 'Ñublense', strength: 69, nation: 'Chile' },
            { name: 'Cobresal', strength: 68, nation: 'Chile' },
            { name: 'Unión La Calera', strength: 68, nation: 'Chile' },
            { name: 'Deportes Iquique', strength: 67, nation: 'Chile' },
            { name: 'Deportes Copiapó', strength: 66, nation: 'Chile' }
        ]
    },
    colombia: {
        label: 'Liga Colômbia',
        teams: [
            { name: 'Atlético Nacional', strength: 80, nation: 'Colômbia' },
            { name: 'Millonarios', strength: 79, nation: 'Colômbia' },
            { name: 'América de Cali', strength: 78, nation: 'Colômbia' },
            { name: 'Junior', strength: 77, nation: 'Colômbia' },
            { name: 'Santa Fe', strength: 76, nation: 'Colômbia' },
            { name: 'Deportivo Cali', strength: 75, nation: 'Colômbia' },
            { name: 'Independiente Medellín', strength: 74, nation: 'Colômbia' },
            { name: 'Once Caldas', strength: 73, nation: 'Colômbia' },
            { name: 'Deportes Tolima', strength: 76, nation: 'Colômbia' },
            { name: 'Águilas Doradas', strength: 73, nation: 'Colômbia' },
            { name: 'Atlético Bucaramanga', strength: 72, nation: 'Colômbia' },
            { name: 'Deportivo Pereira', strength: 72, nation: 'Colômbia' },
            { name: 'La Equidad', strength: 71, nation: 'Colômbia' },
            { name: 'Deportivo Pasto', strength: 70, nation: 'Colômbia' },
            { name: 'Envigado', strength: 69, nation: 'Colômbia' },
            { name: 'Alianza FC', strength: 69, nation: 'Colômbia' },
            { name: 'Boyacá Chicó', strength: 68, nation: 'Colômbia' },
            { name: 'Jaguares de Córdoba', strength: 68, nation: 'Colômbia' },
            { name: 'Fortaleza CEIF', strength: 67, nation: 'Colômbia' },
            { name: 'Patriotas', strength: 67, nation: 'Colômbia' }
        ]
    },
    equador: {
        label: 'Liga Equador',
        teams: [
            { name: 'LDU Quito', strength: 80, nation: 'Equador' },
            { name: 'Barcelona SC', strength: 79, nation: 'Equador' },
            { name: 'Emelec', strength: 78, nation: 'Equador' },
            { name: 'Independiente del Valle', strength: 79, nation: 'Equador' },
            { name: 'Aucas', strength: 74, nation: 'Equador' },
            { name: 'Macará', strength: 72, nation: 'Equador' },
            { name: 'Universidad Católica', strength: 73, nation: 'Equador' },
            { name: 'Delfín', strength: 71, nation: 'Equador' },
            { name: 'El Nacional', strength: 72, nation: 'Equador' },
            { name: 'Deportivo Cuenca', strength: 71, nation: 'Equador' },
            { name: 'Mushuc Runa', strength: 70, nation: 'Equador' },
            { name: 'Técnico Universitario', strength: 70, nation: 'Equador' },
            { name: 'Libertad FC', strength: 69, nation: 'Equador' },
            { name: 'Orense', strength: 69, nation: 'Equador' },
            { name: 'Imbabura', strength: 68, nation: 'Equador' },
            { name: 'Cumbayá', strength: 67, nation: 'Equador' }
        ]
    },
    paraguai: {
        label: 'Liga Paraguai',
        teams: [
            { name: 'Olimpia', strength: 81, nation: 'Paraguai' },
            { name: 'Cerro Porteño', strength: 80, nation: 'Paraguai' },
            { name: 'Libertad', strength: 79, nation: 'Paraguai' },
            { name: 'Guaraní', strength: 76, nation: 'Paraguai' },
            { name: 'Sol de América', strength: 74, nation: 'Paraguai' },
            { name: 'Sportivo Luqueño', strength: 73, nation: 'Paraguai' },
            { name: 'Nacional', strength: 72, nation: 'Paraguai' },
            { name: 'Sportivo Trinidense', strength: 71, nation: 'Paraguai' },
            { name: 'General Caballero JLM', strength: 70, nation: 'Paraguai' },
            { name: 'Tacuary', strength: 70, nation: 'Paraguai' },
            { name: 'Sportivo Ameliano', strength: 70, nation: 'Paraguai' },
            { name: 'Olimpia Asunción', strength: 79, nation: 'Paraguai' },
            { name: 'Cerro de Franco', strength: 69, nation: 'Paraguai' },
            { name: 'Guaireña', strength: 68, nation: 'Paraguai' },
            { name: 'Resistencia', strength: 68, nation: 'Paraguai' },
            { name: 'Deportivo Santaní', strength: 67, nation: 'Paraguai' }
        ]
    },
    peru: {
        label: 'Liga Peru',
        teams: [
            { name: 'Alianza Lima', strength: 79, nation: 'Peru' },
            { name: 'Universitario', strength: 78, nation: 'Peru' },
            { name: 'Sporting Cristal', strength: 80, nation: 'Peru' },
            { name: 'Melgar', strength: 75, nation: 'Peru' },
            { name: 'Cienciano', strength: 73, nation: 'Peru' },
            { name: 'César Vallejo', strength: 74, nation: 'Peru' },
            { name: 'Ayacucho', strength: 71, nation: 'Peru' },
            { name: 'UTC', strength: 70, nation: 'Peru' },
            { name: 'Sport Huancayo', strength: 73, nation: 'Peru' },
            { name: 'Cusco FC', strength: 72, nation: 'Peru' },
            { name: 'Deportivo Garcilaso', strength: 71, nation: 'Peru' },
            { name: 'Alianza Atlético', strength: 70, nation: 'Peru' },
            { name: 'Sport Boys', strength: 70, nation: 'Peru' },
            { name: 'Carlos Mannucci', strength: 69, nation: 'Peru' },
            { name: 'Unión Comercio', strength: 68, nation: 'Peru' },
            { name: 'Atlético Grau', strength: 68, nation: 'Peru' },
            { name: 'Los Chankas', strength: 67, nation: 'Peru' },
            { name: 'Comerciantes Unidos', strength: 67, nation: 'Peru' }
        ]
    },
    uruguai: {
        label: 'Liga Uruguai',
        teams: [
            { name: 'Peñarol', strength: 84, nation: 'Uruguai' },
            { name: 'Nacional', strength: 84, nation: 'Uruguai' },
            { name: 'Defensor Sporting', strength: 77, nation: 'Uruguai' },
            { name: 'Danubio', strength: 74, nation: 'Uruguai' },
            { name: 'Montevideo City', strength: 76, nation: 'Uruguai' },
            { name: 'River Plate', strength: 74, nation: 'Uruguai' },
            { name: 'Wanderers', strength: 73, nation: 'Uruguai' },
            { name: 'Cerro', strength: 72, nation: 'Uruguai' },
            { name: 'Liverpool FC', strength: 77, nation: 'Uruguai' },
            { name: 'Boston River', strength: 73, nation: 'Uruguai' },
            { name: 'Fénix', strength: 71, nation: 'Uruguai' },
            { name: 'Deportivo Maldonado', strength: 70, nation: 'Uruguai' },
            { name: 'Racing de Montevideo', strength: 70, nation: 'Uruguai' },
            { name: 'Progreso', strength: 69, nation: 'Uruguai' },
            { name: 'Miramar Misiones', strength: 68, nation: 'Uruguai' },
            { name: 'Cerro Largo', strength: 68, nation: 'Uruguai' }
        ]
    },
};

export default leagueData;