const leagueData = {
    worldCup: {
        label: 'Copa do Mundo',
        teams: [
            { name: 'Alemanha', strength: 91, nation: 'Alemanha' },
            { name: 'Inglaterra', strength: 90, nation: 'Inglaterra' },
            { name: 'França', strength: 89, nation: 'França' },
            { name: 'Itália', strength: 88, nation: 'Itália' },
            { name: 'Espanha', strength: 87, nation: 'Espanha' },
            { name: 'Portugal', strength: 86, nation: 'Portugal' },
            { name: 'Holanda', strength: 85, nation: 'Países Baixos' },
            { name: 'Bélgica', strength: 84, nation: 'Bélgica' },
            { name: 'Croácia', strength: 83, nation: 'Croácia' },
            { name: 'Suíça', strength: 82, nation: 'Suíça' },
            { name: 'Suécia', strength: 81, nation: 'Suécia' },
            { name: 'Polônia', strength: 80, nation: 'Polônia' },
            { name: 'Áustria', strength: 79, nation: 'Áustria' },
            { name: 'Dinamarca', strength: 78, nation: 'Dinamarca' },
            { name: 'Rússia', strength: 77, nation: 'Rússia' },
            { name: 'Ucrânia', strength: 76, nation: 'Ucrânia' },
            { name: 'Turquia', strength: 75, nation: 'Turquia' },
            { name: 'República Tcheca', strength: 74, nation: 'República Tcheca' },
            { name: 'Escócia', strength: 73, nation: 'Escócia' },
            { name: 'Sérvia', strength: 72, nation: 'Sérvia' },
            { name: 'País de Gales', strength: 71, nation: 'País de Gales' },
            { name: 'Irlanda', strength: 70, nation: 'Irlanda' },
            { name: 'Irlanda do Norte', strength: 69, nation: 'Irlanda do Norte' },
            { name: 'Romênia', strength: 68, nation: 'Romênia' },
            { name: 'Grécia', strength: 67, nation: 'Grécia' },
            { name: 'Hungria', strength: 66, nation: 'Hungria' },
            { name: 'Bulgária', strength: 65, nation: 'Bulgária' },
            { name: 'Noruega', strength: 64, nation: 'Noruega' },
            { name: 'Eslováquia', strength: 63, nation: 'Eslováquia' },
            { name: 'Eslovênia', strength: 62, nation: 'Eslovênia' },
            { name: 'Bósnia e Herzegovina', strength: 61, nation: 'Bósnia e Herzegovina' },
            { name: 'Finlândia', strength: 60, nation: 'Finlândia' },
            { name: 'Islândia', strength: 59, nation: 'Islândia' },
            { name: 'Brasil', strength: 92, nation: 'Brasil' },
            { name: 'Argentina', strength: 91, nation: 'Argentina' },
            { name: 'Uruguai', strength: 90, nation: 'Uruguai' },
            { name: 'México', strength: 84, nation: 'México' },
            { name: 'Estados Unidos', strength: 83, nation: 'Estados Unidos' },
            { name: 'Canadá', strength: 82, nation: 'Canadá' },
            { name: 'Colômbia', strength: 81, nation: 'Colômbia' },
            { name: 'Chile', strength: 80, nation: 'Chile' },
            { name: 'Paraguai', strength: 79, nation: 'Paraguai' },
            { name: 'Equador', strength: 78, nation: 'Equador' },
            { name: 'Peru', strength: 77, nation: 'Peru' },
            { name: 'Costa Rica', strength: 76, nation: 'Costa Rica' },
            { name: 'Jamaica', strength: 75, nation: 'Jamaica' },
            { name: 'Honduras', strength: 74, nation: 'Honduras' },
            { name: 'Panamá', strength: 73, nation: 'Panamá' },
            { name: 'El Salvador', strength: 72, nation: 'El Salvador' },
            { name: 'Haiti', strength: 71, nation: 'Haiti' },
            { name: 'Curaçau', strength: 70, nation: 'Curaçau' },
            { name: 'Trindade e Tobago', strength: 69, nation: 'Trindade e Tobago' },
            { name: 'Nigéria', strength: 68, nation: 'Nigéria' },
            { name: 'Marrocos', strength: 67, nation: 'Marrocos' },
            { name: 'Senegal', strength: 66, nation: 'Senegal' },
            { name: 'Camarões', strength: 65, nation: 'Camarões' },
            { name: 'Gana', strength: 64, nation: 'Gana' },
            { name: 'Egito', strength: 63, nation: 'Egito' },
            { name: 'Argélia', strength: 62, nation: 'Argélia' },
            { name: 'Tunísia', strength: 61, nation: 'Tunísia' },
            { name: 'África do Sul', strength: 60, nation: 'África do Sul' },
            { name: 'Costa do Marfim', strength: 59, nation: 'Costa do Marfim' },
            { name: 'Angola', strength: 58, nation: 'Angola' },
            { name: 'Cabo Verde', strength: 57, nation: 'Cabo Verde' },
            { name: 'RD Congo', strength: 56, nation: 'RD Congo' },
            { name: 'Mali', strength: 55, nation: 'Mali' },
            { name: 'Zâmbia', strength: 54, nation: 'Zâmbia' },
            { name: 'Japão', strength: 80, nation: 'Japão' },
            { name: 'Coreia do Sul', strength: 79, nation: 'Coreia do Sul' },
            { name: 'Austrália', strength: 78, nation: 'Austrália' },
            { name: 'Arábia Saudita', strength: 77, nation: 'Arábia Saudita' },
            { name: 'Irã', strength: 76, nation: 'Irã' },
            { name: 'China', strength: 75, nation: 'China' },
            { name: 'Coreia do Norte', strength: 74, nation: 'Coreia do Norte' },
            { name: 'Emirados Árabes Unidos', strength: 73, nation: 'Emirados Árabes Unidos' },
            { name: 'Catar', strength: 72, nation: 'Catar' },
            { name: 'Iraque', strength: 71, nation: 'Iraque' },
            { name: 'Uzbequistão', strength: 70, nation: 'Uzbequistão' },
            { name: 'Jordânia', strength: 69, nation: 'Jordânia' },
            { name: 'Nova Zelândia', strength: 68, nation: 'Nova Zelândia' },
            { name: 'Iugoslávia', strength: 67, nation: 'Iugoslávia' },
            { name: 'Tchecoslováquia', strength: 66, nation: 'Tchecoslováquia' },
            { name: 'União Soviética', strength: 65, nation: 'União Soviética' },
            { name: 'Indonésia', strength: 64, nation: 'Indonésia' }
        ]
    },
    libertadores: {
        label: 'Libertadores',
        leagues: ['brasil', 'argentina', 'bolivia', 'chile', 'colombia', 'equador', 'paraguai', 'peru', 'uruguai', 'venezuela']
    },
    brasil: {
        label: 'Liga Brasil',
        teams: [
            { image: 'img/brasil/fla_br.png', name: 'Flamengo', strength: 88, nation: 'Brasil' },
            { image: 'img/brasil/bota_br.png', name: 'Botafogo', strength: 88, nation: 'Brasil' },
            { image: 'img/brasil/pal_br.png', name: 'Palmeiras', strength: 87, nation: 'Brasil' },
            { image: 'img/brasil/forta_br.png', name: 'Fortaleza', strength: 85, nation: 'Brasil' },
            { image: 'img/brasil/sp_br.png', name: 'São Paulo', strength: 84, nation: 'Brasil' },
            { image: 'img/brasil/inter_br.svg', name: 'Internacional', strength: 84, nation: 'Brasil' },
            { image: 'img/brasil/mineiro_br.png', name: 'Atlético Mineiro', strength: 83, nation: 'Brasil' },
            { image: 'img/brasil/cru_br.png', name: 'Cruzeiro', strength: 83, nation: 'Brasil' },
            { image: 'img/brasil/bahia_br.png', name: 'Bahia', strength: 83, nation: 'Brasil' },
            { image: 'img/brasil/cor_br.png', name: 'Corinthians', strength: 82, nation: 'Brasil' },
            { image: 'img/brasil/vasco_br.png', name: 'Vasco', strength: 81, nation: 'Brasil' },
            { image: 'img/brasil/gremio_br.png', name: 'Grêmio', strength: 81, nation: 'Brasil' },
            { image: 'img/brasil/flu_br.png', name: 'Fluminense', strength: 80, nation: 'Brasil' },
            { image: 'img/brasil/santos_br.png', name: 'Santos', strength: 79, nation: 'Brasil' },
            { image: 'img/brasil/vitoria_br.png', name: 'Vitória', strength: 77, nation: 'Brasil' },
            { image: 'img/brasil/cri_br.png', name: 'Criciúma', strength: 76, nation: 'Brasil' },
            { image: 'img/brasil/juve_br.png', name: 'Juventude', strength: 76, nation: 'Brasil' },
            { image: 'img/brasil/cuia_br.png', name: 'Cuiaba', strength: 75, nation: 'Brasil' },
            { image: 'img/brasil/ceara_br.png', name: 'Ceará', strength: 75, nation: 'Brasil' },
            { image: 'img/brasil/mira_br.png', name: 'Mirassol', strength: 74, nation: 'Brasil' }
        ]
    },
    italia: {
        label: 'Liga Itália',
        teams: [
            { image: 'img/italia/juventus.svg', name: 'Juventus', strength: 87, nation: 'Itália' },
            { image: 'img/italia/internazionale.svg', name: 'Inter de Milão', strength: 88, nation: 'Itália' },
            { image: 'img/italia/milan.svg', name: 'Milan', strength: 85, nation: 'Itália' },
            { image: 'img/italia/napoli.svg', name: 'Napoli', strength: 86, nation: 'Itália' },
            { image: 'img/italia/roma.svg', name: 'Roma', strength: 83, nation: 'Itália' },
            { image: 'img/italia/lazio.svg', name: 'Lazio', strength: 82, nation: 'Itália' },
            { image: 'img/italia/atalanta.svg', name: 'Atalanta', strength: 84, nation: 'Itália' },
            { image: 'img/italia/fiorentina.svg', name: 'Fiorentina', strength: 80, nation: 'Itália' },
            { image: 'img/italia/bologna.svg', name: 'Bologna', strength: 81, nation: 'Itália' },
            { image: 'img/italia/torino.svg', name: 'Torino', strength: 78, nation: 'Itália' },
            { image: 'img/italia/genoa.svg', name: 'Genoa', strength: 77, nation: 'Itália' },
            { image: 'img/italia/monza.svg', name: 'Monza', strength: 76, nation: 'Itália' },
            { image: 'img/italia/udinese.svg', name: 'Udinese', strength: 76, nation: 'Itália' },
            { image: 'img/italia/verona.png', name: 'Hellas Verona', strength: 75, nation: 'Itália' },
            { image: 'img/italia/lecce.svg', name: 'Lecce', strength: 75, nation: 'Itália' },
            { image: 'img/italia/cagliari.svg', name: 'Cagliari', strength: 74, nation: 'Itália' },
            { image: 'img/italia/empoli.png', name: 'Empoli', strength: 74, nation: 'Itália' },
            { image: 'img/italia/parma.svg', name: 'Parma', strength: 74, nation: 'Itália' },
            { image: 'img/italia/como.svg', name: 'Como', strength: 73, nation: 'Itália' },
            { image: 'img/italia/venezia.svg', name: 'Venezia', strength: 73, nation: 'Itália' }
        ]
    },
    inglaterra: {
        label: 'Liga Inglaterra',
        teams: [
            { name: 'Manchester City', strength: 94, nation: 'Inglaterra' },
            { name: 'Liverpool', strength: 91, nation: 'Inglaterra' },
            { name: 'Chelsea', strength: 89, nation: 'Inglaterra' },
            { name: 'Manchester United', strength: 88, nation: 'Inglaterra' },
            { name: 'Arsenal', strength: 90, nation: 'Inglaterra' },
            { name: 'Tottenham', strength: 86, nation: 'Inglaterra' },
            { name: 'Newcastle', strength: 85, nation: 'Inglaterra' },
            { name: 'Aston Villa', strength: 80, nation: 'Inglaterra' },
            { name: 'West Ham', strength: 79, nation: 'Inglaterra' },
            { name: 'Brighton', strength: 79, nation: 'Inglaterra' },
            { name: 'Crystal Palace', strength: 78, nation: 'Inglaterra' },
            { name: 'Fulham', strength: 77, nation: 'Inglaterra' },
            { name: 'Bournemouth', strength: 77, nation: 'Inglaterra' },
            { name: 'Everton', strength: 76, nation: 'Inglaterra' },
            { name: 'Wolverhampton', strength: 76, nation: 'Inglaterra' },
            { name: 'Nottingham Forest', strength: 76, nation: 'Inglaterra' },
            { name: 'Brentford', strength: 75, nation: 'Inglaterra' },
            { name: 'Leicester City', strength: 75, nation: 'Inglaterra' },
            { name: 'Southampton', strength: 74, nation: 'Inglaterra' },
            { name: 'Sheffield United', strength: 73, nation: 'Inglaterra' }
        ]
    },
    franca: {
        label: 'Liga França',
        teams: [
            { name: 'Paris Saint-Germain', strength: 91, nation: 'França' },
            { name: 'Marseille', strength: 83, nation: 'França' },
            { name: 'Lyon', strength: 82, nation: 'França' },
            { name: 'Monaco', strength: 84, nation: 'França' },
            { name: 'Rennes', strength: 80, nation: 'França' },
            { name: 'Lille', strength: 82, nation: 'França' },
            { name: 'Nice', strength: 79, nation: 'França' },
            { name: 'Nantes', strength: 78, nation: 'França' },
            { name: 'Lens', strength: 81, nation: 'França' },
            { name: 'Brest', strength: 80, nation: 'França' },
            { name: 'Reims', strength: 77, nation: 'França' },
            { name: 'Toulouse', strength: 77, nation: 'França' },
            { name: 'Strasbourg', strength: 76, nation: 'França' },
            { name: 'Montpellier', strength: 76, nation: 'França' },
            { name: 'Le Havre', strength: 75, nation: 'França' },
            { name: 'Saint-Étienne', strength: 75, nation: 'França' },
            { name: 'Auxerre', strength: 74, nation: 'França' },
            { name: 'Angers', strength: 73, nation: 'França' }
        ]
    },
    alemanha: {
        label: 'Liga Alemanha',
        teams: [
            { name: 'Bayern de Munique', strength: 92, nation: 'Alemanha' },
            { name: 'Bayer Leverkusen', strength: 89, nation: 'Alemanha' },
            { name: 'Borussia Dortmund', strength: 86, nation: 'Alemanha' },
            { name: 'RB Leipzig', strength: 85, nation: 'Alemanha' },
            { name: 'VfB Stuttgart', strength: 83, nation: 'Alemanha' },
            { name: 'Eintracht Frankfurt', strength: 81, nation: 'Alemanha' },
            { name: 'Freiburg', strength: 79, nation: 'Alemanha' },
            { name: 'Hoffenheim', strength: 78, nation: 'Alemanha' },
            { name: 'Wolfsburg', strength: 77, nation: 'Alemanha' },
            { name: 'Borussia Mönchengladbach', strength: 77, nation: 'Alemanha' },
            { name: 'Werder Bremen', strength: 76, nation: 'Alemanha' },
            { name: 'Union Berlin', strength: 76, nation: 'Alemanha' },
            { name: 'Heidenheim', strength: 75, nation: 'Alemanha' },
            { name: 'Mainz 05', strength: 75, nation: 'Alemanha' },
            { name: 'Augsburg', strength: 74, nation: 'Alemanha' },
            { name: 'Bochum', strength: 73, nation: 'Alemanha' },
            { name: 'St. Pauli', strength: 73, nation: 'Alemanha' },
            { name: 'Holstein Kiel', strength: 72, nation: 'Alemanha' }
        ]
    },
    espanha: {
        label: 'Liga Espanha',
        teams: [
            { name: 'Real Madrid', strength: 95, nation: 'Espanha' },
            { name: 'Barcelona', strength: 92, nation: 'Espanha' },
            { name: 'Atlético de Madrid', strength: 87, nation: 'Espanha' },
            { name: 'Sevilla', strength: 84, nation: 'Espanha' },
            { name: 'Valencia', strength: 80, nation: 'Espanha' },
            { name: 'Villarreal', strength: 82, nation: 'Espanha' },
            { name: 'Real Sociedad', strength: 83, nation: 'Espanha' },
            { name: 'Athletic Club', strength: 81, nation: 'Espanha' },
            { name: 'Girona', strength: 84, nation: 'Espanha' },
            { name: 'Real Betis', strength: 82, nation: 'Espanha' },
            { name: 'Osasuna', strength: 78, nation: 'Espanha' },
            { name: 'Celta de Vigo', strength: 77, nation: 'Espanha' },
            { name: 'Getafe', strength: 77, nation: 'Espanha' },
            { name: 'Mallorca', strength: 76, nation: 'Espanha' },
            { name: 'Alavés', strength: 75, nation: 'Espanha' },
            { name: 'Rayo Vallecano', strength: 75, nation: 'Espanha' },
            { name: 'Las Palmas', strength: 74, nation: 'Espanha' },
            { name: 'Espanyol', strength: 74, nation: 'Espanha' },
            { name: 'Real Valladolid', strength: 73, nation: 'Espanha' },
            { name: 'Leganés', strength: 73, nation: 'Espanha' }
        ]
    },
    argentina: {
        label: 'Liga Argentina',
        teams: [
            { name: 'Boca Juniors', strength: 86, nation: 'Argentina' },
            { name: 'River Plate', strength: 87, nation: 'Argentina' },
            { name: 'Racing Club', strength: 82, nation: 'Argentina' },
            { name: 'San Lorenzo', strength: 78, nation: 'Argentina' },
            { name: 'Independiente', strength: 80, nation: 'Argentina' },
            { name: 'Vélez Sarsfield', strength: 79, nation: 'Argentina' },
            { name: 'Estudiantes', strength: 81, nation: 'Argentina' },
            { name: 'Talleres', strength: 80, nation: 'Argentina' },
            { name: 'Defensa y Justicia', strength: 79, nation: 'Argentina' },
            { name: 'Rosario Central', strength: 78, nation: 'Argentina' },
            { name: 'Argentinos Juniors', strength: 78, nation: 'Argentina' },
            { name: 'Lanús', strength: 77, nation: 'Argentina' },
            { name: 'Newell\'s Old Boys', strength: 77, nation: 'Argentina' },
            { name: 'Godoy Cruz', strength: 77, nation: 'Argentina' },
            { name: 'Huracán', strength: 76, nation: 'Argentina' },
            { name: 'Belgrano', strength: 76, nation: 'Argentina' },
            { name: 'Banfield', strength: 75, nation: 'Argentina' },
            { name: 'Gimnasia (LP)', strength: 75, nation: 'Argentina' },
            { name: 'Unión', strength: 74, nation: 'Argentina' },
            { name: 'Tigre', strength: 74, nation: 'Argentina' },
            { name: 'Instituto', strength: 74, nation: 'Argentina' },
            { name: 'Atlético Tucumán', strength: 73, nation: 'Argentina' },
            { name: 'Platense', strength: 73, nation: 'Argentina' },
            { name: 'Central Córdoba', strength: 72, nation: 'Argentina' },
            { name: 'Sarmiento', strength: 71, nation: 'Argentina' },
            { name: 'Barracas Central', strength: 71, nation: 'Argentina' },
            { name: 'Independiente Rivadavia', strength: 70, nation: 'Argentina' },
            { name: 'Deportivo Riestra', strength: 69, nation: 'Argentina' }
        ]
    },
    usa: {
        label: 'Liga USA',
        teams: [
            { name: 'LA Galaxy', strength: 78, nation: 'Estados Unidos' },
            { name: 'LAFC', strength: 80, nation: 'Estados Unidos' },
            { name: 'NYCFC', strength: 79, nation: 'Estados Unidos' },
            { name: 'Inter Miami', strength: 78, nation: 'Estados Unidos' },
            { name: 'Seattle Sounders', strength: 80, nation: 'Estados Unidos' },
            { name: 'Atlanta United', strength: 77, nation: 'Estados Unidos' },
            { name: 'FC Dallas', strength: 76, nation: 'Estados Unidos' },
            { name: 'Philadelphia Union', strength: 75, nation: 'Estados Unidos' },
            { name: 'Columbus Crew', strength: 81, nation: 'Estados Unidos' },
            { name: 'FC Cincinnati', strength: 80, nation: 'Estados Unidos' },
            { name: 'New York Red Bulls', strength: 76, nation: 'Estados Unidos' },
            { name: 'Orlando City', strength: 77, nation: 'Estados Unidos' },
            { name: 'Real Salt Lake', strength: 77, nation: 'Estados Unidos' },
            { name: 'Houston Dynamo', strength: 76, nation: 'Estados Unidos' },
            { name: 'Portland Timbers', strength: 76, nation: 'Estados Unidos' },
            { name: 'St. Louis City SC', strength: 76, nation: 'Estados Unidos' },
            { name: 'New England Revolution', strength: 75, nation: 'Estados Unidos' },
            { name: 'Minnesota United', strength: 75, nation: 'Estados Unidos' },
            { name: 'Charlotte FC', strength: 75, nation: 'Estados Unidos' },
            { name: 'Nashville SC', strength: 75, nation: 'Estados Unidos' },
            { name: 'Vancouver Whitecaps', strength: 75, nation: 'Canadá' },
            { name: 'Austin FC', strength: 74, nation: 'Estados Unidos' },
            { name: 'Colorado Rapids', strength: 74, nation: 'Estados Unidos' },
            { name: 'Sporting Kansas City', strength: 74, nation: 'Estados Unidos' },
            { name: 'Toronto FC', strength: 74, nation: 'Canadá' },
            { name: 'D.C. United', strength: 73, nation: 'Estados Unidos' },
            { name: 'CF Montréal', strength: 73, nation: 'Canadá' },
            { name: 'San Jose Earthquakes', strength: 72, nation: 'Estados Unidos' },
            { name: 'Chicago Fire', strength: 72, nation: 'Estados Unidos' },
            { name: 'San Diego FC', strength: 72, nation: 'Estados Unidos' }
        ]
    },
    japao: {
        label: 'Liga Japão',
        teams: [
            { name: 'Kawasaki Frontale', strength: 78, nation: 'Japão' },
            { name: 'Yokohama F. Marinos', strength: 79, nation: 'Japão' },
            { name: 'Urawa Reds', strength: 77, nation: 'Japão' },
            { name: 'Kashima Antlers', strength: 76, nation: 'Japão' },
            { name: 'Gamba Osaka', strength: 75, nation: 'Japão' },
            { name: 'FC Tokyo', strength: 74, nation: 'Japão' },
            { name: 'Cerezo Osaka', strength: 74, nation: 'Japão' },
            { name: 'Nagoya Grampus', strength: 75, nation: 'Japão' },
            { name: 'Vissel Kobe', strength: 79, nation: 'Japão' },
            { name: 'Sanfrecce Hiroshima', strength: 78, nation: 'Japão' },
            { name: 'Machida Zelvia', strength: 77, nation: 'Japão' },
            { name: 'Avispa Fukuoka', strength: 74, nation: 'Japão' },
            { name: 'Kashiwa Reysol', strength: 73, nation: 'Japão' },
            { name: 'Consadole Sapporo', strength: 73, nation: 'Japão' },
            { name: 'Albirex Niigata', strength: 73, nation: 'Japão' },
            { name: 'Kyoto Sanga', strength: 72, nation: 'Japão' },
            { name: 'Jubilo Iwata', strength: 72, nation: 'Japão' },
            { name: 'Sagan Tosu', strength: 71, nation: 'Japão' },
            { name: 'Shonan Bellmare', strength: 71, nation: 'Japão' },
            { name: 'Tokyo Verdy', strength: 70, nation: 'Japão' }
        ]
    },
    belgica_a: {
        label: 'Liga Bélgica',
        teams: [
            { name: 'Club Brugge', strength: 80, nation: 'Bélgica' },
            { name: 'Anderlecht', strength: 78, nation: 'Bélgica' },
            { name: 'Genk', strength: 77, nation: 'Bélgica' },
            { name: 'Gent', strength: 76, nation: 'Bélgica' },
            { name: 'Standard de Liège', strength: 74, nation: 'Bélgica' },
            { name: 'Antwerp', strength: 75, nation: 'Bélgica' },
            { name: 'Brugge KV', strength: 73, nation: 'Bélgica' },
            { name: 'Mechelen', strength: 72, nation: 'Bélgica' },
            { name: 'Union Saint-Gilloise', strength: 79, nation: 'Bélgica' },
            { name: 'Charleroi', strength: 72, nation: 'Bélgica' },
            { name: 'Sint-Truiden', strength: 71, nation: 'Bélgica' },
            { name: 'Westerlo', strength: 71, nation: 'Bélgica' },
            { name: 'OH Leuven', strength: 70, nation: 'Bélgica' },
            { name: 'Kortrijk', strength: 69, nation: 'Bélgica' },
            { name: 'Dender', strength: 68, nation: 'Bélgica' },
            { name: 'Beerschot', strength: 68, nation: 'Bélgica' }
        ]
    },
    holanda: {
        label: 'Liga Holanda',
        teams: [
            { name: 'Ajax', strength: 84, nation: 'Holanda' },
            { name: 'PSV', strength: 82, nation: 'Holanda' },
            { name: 'Feyenoord', strength: 81, nation: 'Holanda' },
            { name: 'AZ Alkmaar', strength: 78, nation: 'Holanda' },
            { name: 'Twente', strength: 76, nation: 'Holanda' },
            { name: 'Utrecht', strength: 75, nation: 'Holanda' },
            { name: 'Heerenveen', strength: 73, nation: 'Holanda' },
            { name: 'Vitesse', strength: 74, nation: 'Holanda' },
            { name: 'NEC Nijmegen', strength: 74, nation: 'Holanda' },
            { name: 'Sparta Rotterdam', strength: 73, nation: 'Holanda' },
            { name: 'Go Ahead Eagles', strength: 72, nation: 'Holanda' },
            { name: 'FC Groningen', strength: 72, nation: 'Holanda' },
            { name: 'Fortuna Sittard', strength: 71, nation: 'Holanda' },
            { name: 'PEC Zwolle', strength: 71, nation: 'Holanda' },
            { name: 'Heracles Almelo', strength: 70, nation: 'Holanda' },
            { name: 'Willem II', strength: 70, nation: 'Holanda' },
            { name: 'Almere City', strength: 69, nation: 'Holanda' },
            { name: 'RKC Waalwijk', strength: 69, nation: 'Holanda' }
        ]
    },
    noruega: {
        label: 'Liga Noruega',
        teams: [
            { name: 'Rosenborg', strength: 76, nation: 'Noruega' },
            { name: 'Molde', strength: 77, nation: 'Noruega' },
            { name: 'Bodø/Glimt', strength: 78, nation: 'Noruega' },
            { name: 'Viking', strength: 74, nation: 'Noruega' },
            { name: 'Brann', strength: 73, nation: 'Noruega' },
            { name: 'Lillestrøm', strength: 72, nation: 'Noruega' },
            { name: 'Sarpsborg', strength: 71, nation: 'Noruega' },
            { name: 'Tromsø', strength: 70, nation: 'Noruega' },
            { name: 'Strømsgodset', strength: 71, nation: 'Noruega' },
            { name: 'Odd', strength: 70, nation: 'Noruega' },
            { name: 'Fredrikstad', strength: 70, nation: 'Noruega' },
            { name: 'Haugesund', strength: 69, nation: 'Noruega' },
            { name: 'HamKam', strength: 68, nation: 'Noruega' },
            { name: 'Sandefjord', strength: 67, nation: 'Noruega' },
            { name: 'Kristiansund', strength: 67, nation: 'Noruega' },
            { name: 'KFUM Oslo', strength: 66, nation: 'Noruega' }
        ]
    },
    portugal: {
        label: 'Liga Portugal',
        teams: [
            { name: 'Porto', strength: 87, nation: 'Portugal' },
            { name: 'Benfica', strength: 88, nation: 'Portugal' },
            { name: 'Sporting', strength: 86, nation: 'Portugal' },
            { name: 'Braga', strength: 82, nation: 'Portugal' },
            { name: 'Guimarães', strength: 79, nation: 'Portugal' },
            { name: 'Famalicão', strength: 76, nation: 'Portugal' },
            { name: 'Boavista', strength: 75, nation: 'Portugal' },
            { name: 'Vitória SC', strength: 74, nation: 'Portugal' },
            { name: 'Rio Ave', strength: 75, nation: 'Portugal' },
            { name: 'Arouca', strength: 75, nation: 'Portugal' },
            { name: 'Casa Pia', strength: 74, nation: 'Portugal' },
            { name: 'Gil Vicente', strength: 73, nation: 'Portugal' },
            { name: 'Estoril Praia', strength: 73, nation: 'Portugal' },
            { name: 'Farense', strength: 72, nation: 'Portugal' },
            { name: 'Estrela da Amadora', strength: 72, nation: 'Portugal' },
            { name: 'Moreirense', strength: 74, nation: 'Portugal' },
            { name: 'Nacional', strength: 71, nation: 'Portugal' },
            { name: 'Santa Clara', strength: 72, nation: 'Portugal' }
        ]
    },
    suecia: {
        label: 'Liga Suécia',
        teams: [
            { name: 'Malmö FF', strength: 76, nation: 'Suécia' },
            { name: 'Djurgårdens IF', strength: 74, nation: 'Suécia' },
            { name: 'BK Häcken', strength: 74, nation: 'Suécia' },
            { name: 'IF Elfsborg', strength: 73, nation: 'Suécia' },
            { name: 'Hammarby IF', strength: 72, nation: 'Suécia' },
            { name: 'AIK', strength: 72, nation: 'Suécia' },
            { name: 'IFK Göteborg', strength: 71, nation: 'Suécia' },
            { name: 'IFK Norrköping', strength: 70, nation: 'Suécia' },
            { name: 'Kalmar FF', strength: 69, nation: 'Suécia' },
            { name: 'Sirius', strength: 69, nation: 'Suécia' },
            { name: 'Mjällby AIF', strength: 69, nation: 'Suécia' },
            { name: 'Halmstads BK', strength: 68, nation: 'Suécia' },
            { name: 'IFK Värnamo', strength: 68, nation: 'Suécia' },
            { name: 'GAIS', strength: 68, nation: 'Suécia' },
            { name: 'Brommapojkarna', strength: 67, nation: 'Suécia' },
            { name: 'Västerås SK', strength: 67, nation: 'Suécia' }
        ]
    },
    mexico: {
        label: 'Liga México',
        teams: [
            { name: 'América', strength: 85, nation: 'México' },
            { name: 'Chivas', strength: 84, nation: 'México' },
            { name: 'Cruz Azul', strength: 82, nation: 'México' },
            { name: 'Pumas', strength: 81, nation: 'México' },
            { name: 'Monterrey', strength: 83, nation: 'México' },
            { name: 'Tigres', strength: 83, nation: 'México' },
            { name: 'Santos Laguna', strength: 80, nation: 'México' },
            { name: 'Atlas', strength: 79, nation: 'México' },
            { name: 'Toluca', strength: 80, nation: 'México' },
            { name: 'Pachuca', strength: 80, nation: 'México' },
            { name: 'León', strength: 79, nation: 'México' },
            { name: 'Querétaro', strength: 77, nation: 'México' },
            { name: 'Atlético San Luis', strength: 77, nation: 'México' },
            { name: 'Necaxa', strength: 76, nation: 'México' },
            { name: 'Tijuana', strength: 76, nation: 'México' },
            { name: 'Puebla', strength: 75, nation: 'México' },
            { name: 'Mazatlán', strength: 74, nation: 'México' },
            { name: 'Juárez', strength: 74, nation: 'México' }
        ]
    },
    venezuela: {
        label: 'Liga Venezuela',
        teams: [
            { name: 'Caracas', strength: 72, nation: 'Venezuela' },
            { name: 'Deportivo Táchira', strength: 73, nation: 'Venezuela' },
            { name: 'Zamora', strength: 71, nation: 'Venezuela' },
            { name: 'Monagas', strength: 70, nation: 'Venezuela' },
            { name: 'Portuguesa', strength: 69, nation: 'Venezuela' },
            { name: 'Estudiantes de Mérida', strength: 68, nation: 'Venezuela' },
            { name: 'La Guaira', strength: 68, nation: 'Venezuela' },
            { name: 'Trujillanos', strength: 67, nation: 'Venezuela' },
            { name: 'Carabobo FC', strength: 70, nation: 'Venezuela' },
            { name: 'Metropolitanos', strength: 70, nation: 'Venezuela' },
            { name: 'Academia Puerto Cabello', strength: 69, nation: 'Venezuela' },
            { name: 'Angostura FC', strength: 67, nation: 'Venezuela' },
            { name: 'Inter de Barinas', strength: 66, nation: 'Venezuela' },
            { name: 'Rayo Zuliano', strength: 66, nation: 'Venezuela' },
            { name: 'Universidad Central', strength: 65, nation: 'Venezuela' },
            { name: 'Deportivo Lara', strength: 65, nation: 'Venezuela' }
        ]
    },
    suica: {
        label: 'Liga Suíça',
        teams: [
            { name: 'Young Boys', strength: 80, nation: 'Suíça' },
            { name: 'Basel', strength: 79, nation: 'Suíça' },
            { name: 'Zurique', strength: 77, nation: 'Suíça' },
            { name: 'Lugano', strength: 76, nation: 'Suíça' },
            { name: 'St. Gallen', strength: 75, nation: 'Suíça' },
            { name: 'Servette', strength: 74, nation: 'Suíça' },
            { name: 'Luzern', strength: 74, nation: 'Suíça' },
            { name: 'Sion', strength: 73, nation: 'Suíça' },
            { name: 'Grasshopper', strength: 72, nation: 'Suíça' },
            { name: 'Winterthur', strength: 71, nation: 'Suíça' },
            { name: 'Lausanne-Sport', strength: 71, nation: 'Suíça' },
            { name: 'Yverdon-Sport', strength: 70, nation: 'Suíça' }
        ]
    },
    turquia: {
        label: 'Liga Turquia',
        teams: [
            { name: 'Galatasaray', strength: 83, nation: 'Turquia' },
            { name: 'Fenerbahçe', strength: 82, nation: 'Turquia' },
            { name: 'Besiktas', strength: 82, nation: 'Turquia' },
            { name: 'Trabzonspor', strength: 80, nation: 'Turquia' },
            { name: 'Istanbul Basaksehir', strength: 78, nation: 'Turquia' },
            { name: 'Sivasspor', strength: 76, nation: 'Turquia' },
            { name: 'Alanyaspor', strength: 75, nation: 'Turquia' },
            { name: 'Rizespor', strength: 74, nation: 'Turquia' },
            { name: 'Kasimpasa', strength: 74, nation: 'Turquia' },
            { name: 'Antalyaspor', strength: 73, nation: 'Turquia' },
            { name: 'Gaziantep FK', strength: 73, nation: 'Turquia' },
            { name: 'Adana Demirspor', strength: 73, nation: 'Turquia' },
            { name: 'Samsunspor', strength: 72, nation: 'Turquia' },
            { name: 'Kayserispor', strength: 72, nation: 'Turquia' },
            { name: 'Konyaspor', strength: 71, nation: 'Turquia' },
            { name: 'Ankaragücü', strength: 71, nation: 'Turquia' },
            { name: 'Hatayspor', strength: 70, nation: 'Turquia' },
            { name: 'Eyüpspor', strength: 70, nation: 'Turquia' },
            { name: 'Bodrumspor', strength: 69, nation: 'Turquia' }
        ]
    },
    tcheca: {
        label: 'Liga Tcheca',
        teams: [
            { name: 'Slavia Praga', strength: 82, nation: 'República Tcheca' },
            { name: 'Sparta Praga', strength: 81, nation: 'República Tcheca' },
            { name: 'Viktoria Plzeň', strength: 79, nation: 'República Tcheca' },
            { name: 'Baník Ostrava', strength: 76, nation: 'República Tcheca' },
            { name: 'Sigma Olomouc', strength: 74, nation: 'República Tcheca' },
            { name: 'Slovan Liberec', strength: 73, nation: 'República Tcheca' },
            { name: 'Jablonec', strength: 72, nation: 'República Tcheca' },
            { name: 'Bohemians 1905', strength: 71, nation: 'República Tcheca' },
            { name: 'Mladá Boleslav', strength: 71, nation: 'República Tcheca' },
            { name: 'Slovácko', strength: 70, nation: 'República Tcheca' },
            { name: 'Teplice', strength: 69, nation: 'República Tcheca' },
            { name: 'Hradec Králové', strength: 69, nation: 'República Tcheca' },
            { name: 'Dynamo České Budějovice', strength: 68, nation: 'República Tcheca' },
            { name: 'Pardubice', strength: 68, nation: 'República Tcheca' },
            { name: 'Karviná', strength: 67, nation: 'República Tcheca' },
            { name: 'Dukla Praga', strength: 67, nation: 'República Tcheca' }
        ]
    },
    grecia: {
        label: 'Liga Grécia',
        teams: [
            { name: 'Olympiacos', strength: 82, nation: 'Grécia' },
            { name: 'PAOK', strength: 81, nation: 'Grécia' },
            { name: 'Panathinaikos', strength: 80, nation: 'Grécia' },
            { name: 'AEK Atenas', strength: 80, nation: 'Grécia' },
            { name: 'Aris', strength: 76, nation: 'Grécia' },
            { name: 'OFI Crete', strength: 73, nation: 'Grécia' },
            { name: 'Atromitos', strength: 72, nation: 'Grécia' },
            { name: 'Asteras Tripolis', strength: 72, nation: 'Grécia' },
            { name: 'Panetolikos', strength: 71, nation: 'Grécia' },
            { name: 'Lamia', strength: 70, nation: 'Grécia' },
            { name: 'Volos NFC', strength: 70, nation: 'Grécia' },
            { name: 'Panserraikos', strength: 69, nation: 'Grécia' },
            { name: 'Kallithea', strength: 68, nation: 'Grécia' },
            { name: 'Levadiakos', strength: 68, nation: 'Grécia' }
        ]
    },
    escocia: {
        label: 'Liga Escócia',
        teams: [
            { name: 'Celtic', strength: 83, nation: 'Escócia' },
            { name: 'Rangers', strength: 82, nation: 'Escócia' },
            { name: 'Aberdeen', strength: 76, nation: 'Escócia' },
            { name: 'Hearts', strength: 74, nation: 'Escócia' },
            { name: 'Hibernian', strength: 73, nation: 'Escócia' },
            { name: 'Motherwell', strength: 72, nation: 'Escócia' },
            { name: 'Kilmarnock', strength: 71, nation: 'Escócia' },
            { name: 'St. Johnstone', strength: 70, nation: 'Escócia' },
            { name: 'Dundee FC', strength: 70, nation: 'Escócia' },
            { name: 'St. Mirren', strength: 69, nation: 'Escócia' },
            { name: 'Ross County', strength: 68, nation: 'Escócia' },
            { name: 'Dundee United', strength: 68, nation: 'Escócia' }
        ]
    },
    russia: {
        label: 'Liga Rússia',
        teams: [
            { name: 'Zenit', strength: 83, nation: 'Rússia' },
            { name: 'Spartak Moscou', strength: 80, nation: 'Rússia' },
            { name: 'CSKA Moscou', strength: 79, nation: 'Rússia' },
            { name: 'Lokomotiv Moscou', strength: 79, nation: 'Rússia' },
            { name: 'Dynamo Moscou', strength: 78, nation: 'Rússia' },
            { name: 'FC Krasnodar', strength: 78, nation: 'Rússia' },
            { name: 'FC Rostov', strength: 76, nation: 'Rússia' },
            { name: 'Akhmat Grozny', strength: 75, nation: 'Rússia' },
            { name: 'Krylia Sovetov', strength: 74, nation: 'Rússia' },
            { name: 'Rubin Kazan', strength: 74, nation: 'Rússia' },
            { name: 'Orenburg', strength: 73, nation: 'Rússia' },
            { name: 'Pari NN', strength: 72, nation: 'Rússia' },
            { name: 'Fakel Voronezh', strength: 71, nation: 'Rússia' },
            { name: 'Baltika', strength: 70, nation: 'Rússia' },
            { name: 'Sochi', strength: 70, nation: 'Rússia' },
            { name: 'Khimki', strength: 69, nation: 'Rússia' }
        ]
    },
    arabia: {
        label: 'Liga Arábia',
        teams: [
            { name: 'Al Hilal', strength: 84, nation: 'Arábia Saudita' },
            { name: 'Al Nassr', strength: 83, nation: 'Arábia Saudita' },
            { name: 'Al Ittihad', strength: 82, nation: 'Arábia Saudita' },
            { name: 'Al Ahli', strength: 81, nation: 'Arábia Saudita' },
            { name: 'Al Shabab', strength: 78, nation: 'Arábia Saudita' },
            { name: 'Al Ettifaq', strength: 77, nation: 'Arábia Saudita' },
            { name: 'Al Taawoun', strength: 76, nation: 'Arábia Saudita' },
            { name: 'Al Fateh', strength: 75, nation: 'Arábia Saudita' },
            { name: 'Al Khaleej', strength: 73, nation: 'Arábia Saudita' },
            { name: 'Al Fayha', strength: 73, nation: 'Arábia Saudita' },
            { name: 'Al Raed', strength: 72, nation: 'Arábia Saudita' },
            { name: 'Al Okhdood', strength: 72, nation: 'Arábia Saudita' },
            { name: 'Al Wehda', strength: 71, nation: 'Arábia Saudita' },
            { name: 'Damac FC', strength: 71, nation: 'Arábia Saudita' },
            { name: 'Al Riyadh', strength: 70, nation: 'Arábia Saudita' },
            { name: 'Al Qadsiah', strength: 70, nation: 'Arábia Saudita' },
            { name: 'Al Kholood', strength: 69, nation: 'Arábia Saudita' },
            { name: 'Al Orobah', strength: 68, nation: 'Arábia Saudita' }
        ]
    },
    coreia: {
        label: 'Liga Coreia',
        teams: [
            { name: 'Jeonbuk Hyundai', strength: 79, nation: 'Coreia do Sul' },
            { name: 'Ulsan', strength: 78, nation: 'Coreia do Sul' },
            { name: 'Pohang', strength: 77, nation: 'Coreia do Sul' },
            { name: 'FC Seoul', strength: 76, nation: 'Coreia do Sul' },
            { name: 'Suwon Bluewings', strength: 75, nation: 'Coreia do Sul' },
            { name: 'Daegu', strength: 74, nation: 'Coreia do Sul' },
            { name: 'Incheon', strength: 72, nation: 'Coreia do Sul' },
            { name: 'Gwangju', strength: 70, nation: 'Coreia do Sul' },
            { name: 'Jeju United', strength: 71, nation: 'Coreia do Sul' },
            { name: 'Daejeon Hana Citizen', strength: 70, nation: 'Coreia do Sul' },
            { name: 'Gangwon', strength: 69, nation: 'Coreia do Sul' },
            { name: 'Suwon FC', strength: 68, nation: 'Coreia do Sul' }
        ]
    },
    bolivia: {
        label: 'Liga Bolívia',
        teams: [
            { name: 'Bolívar', strength: 76, nation: 'Bolívia' },
            { name: 'The Strongest', strength: 75, nation: 'Bolívia' },
            { name: 'Jorge Wilstermann', strength: 74, nation: 'Bolívia' },
            { name: 'Oriente Petrolero', strength: 72, nation: 'Bolívia' },
            { name: 'Blooming', strength: 71, nation: 'Bolívia' },
            { name: 'Guabirá', strength: 70, nation: 'Bolívia' },
            { name: 'Royal Pari', strength: 69, nation: 'Bolívia' },
            { name: 'Nacional Potosí', strength: 68, nation: 'Bolívia' },
            { name: 'Always Ready', strength: 72, nation: 'Bolívia' },
            { name: 'Aurora', strength: 71, nation: 'Bolívia' },
            { name: 'Real Tomayapo', strength: 69, nation: 'Bolívia' },
            { name: 'Independiente Petrolero', strength: 68, nation: 'Bolívia' },
            { name: 'Real Santa Cruz', strength: 67, nation: 'Bolívia' },
            { name: 'San Antonio Bulo Bulo', strength: 67, nation: 'Bolívia' },
            { name: 'GV San José', strength: 66, nation: 'Bolívia' },
            { name: 'Universitario de Vinto', strength: 66, nation: 'Bolívia' }
        ]
    },
    chile: {
        label: 'Liga Chile',
        teams: [
            { name: 'Colo-Colo', strength: 78, nation: 'Chile' },
            { name: 'Universidad de Chile', strength: 77, nation: 'Chile' },
            { name: 'Universidad Catolica', strength: 76, nation: 'Chile' },
            { name: 'Cobreloa', strength: 72, nation: 'Chile' },
            { name: 'Palestino', strength: 71, nation: 'Chile' },
            { name: "O'Higgins", strength: 70, nation: 'Chile' },
            { name: 'Everton', strength: 70, nation: 'Chile' },
            { name: 'Audax Italiano', strength: 69, nation: 'Chile' },
            { name: 'Huachipato', strength: 72, nation: 'Chile' },
            { name: 'Coquimbo Unido', strength: 71, nation: 'Chile' },
            { name: 'Unión Española', strength: 70, nation: 'Chile' },
            { name: 'Ñublense', strength: 69, nation: 'Chile' },
            { name: 'Cobresal', strength: 68, nation: 'Chile' },
            { name: 'Unión La Calera', strength: 68, nation: 'Chile' },
            { name: 'Deportes Iquique', strength: 67, nation: 'Chile' },
            { name: 'Deportes Copiapó', strength: 66, nation: 'Chile' }
        ]
    },
    colombia: {
        label: 'Liga Colômbia',
        teams: [
            { name: 'Atlético Nacional', strength: 80, nation: 'Colômbia' },
            { name: 'Millonarios', strength: 79, nation: 'Colômbia' },
            { name: 'América de Cali', strength: 78, nation: 'Colômbia' },
            { name: 'Junior', strength: 77, nation: 'Colômbia' },
            { name: 'Santa Fe', strength: 76, nation: 'Colômbia' },
            { name: 'Deportivo Cali', strength: 75, nation: 'Colômbia' },
            { name: 'Independiente Medellín', strength: 74, nation: 'Colômbia' },
            { name: 'Once Caldas', strength: 73, nation: 'Colômbia' },
            { name: 'Deportes Tolima', strength: 76, nation: 'Colômbia' },
            { name: 'Águilas Doradas', strength: 73, nation: 'Colômbia' },
            { name: 'Atlético Bucaramanga', strength: 72, nation: 'Colômbia' },
            { name: 'Deportivo Pereira', strength: 72, nation: 'Colômbia' },
            { name: 'La Equidad', strength: 71, nation: 'Colômbia' },
            { name: 'Deportivo Pasto', strength: 70, nation: 'Colômbia' },
            { name: 'Envigado', strength: 69, nation: 'Colômbia' },
            { name: 'Alianza FC', strength: 69, nation: 'Colômbia' },
            { name: 'Boyacá Chicó', strength: 68, nation: 'Colômbia' },
            { name: 'Jaguares de Córdoba', strength: 68, nation: 'Colômbia' },
            { name: 'Fortaleza CEIF', strength: 67, nation: 'Colômbia' },
            { name: 'Patriotas', strength: 67, nation: 'Colômbia' }
        ]
    },
    equador: {
        label: 'Liga Equador',
        teams: [
            { name: 'LDU Quito', strength: 80, nation: 'Equador' },
            { name: 'Barcelona SC', strength: 79, nation: 'Equador' },
            { name: 'Emelec', strength: 78, nation: 'Equador' },
            { name: 'Independiente del Valle', strength: 79, nation: 'Equador' },
            { name: 'Aucas', strength: 74, nation: 'Equador' },
            { name: 'Macará', strength: 72, nation: 'Equador' },
            { name: 'Universidad Católica', strength: 73, nation: 'Equador' },
            { name: 'Delfín', strength: 71, nation: 'Equador' },
            { name: 'El Nacional', strength: 72, nation: 'Equador' },
            { name: 'Deportivo Cuenca', strength: 71, nation: 'Equador' },
            { name: 'Mushuc Runa', strength: 70, nation: 'Equador' },
            { name: 'Técnico Universitario', strength: 70, nation: 'Equador' },
            { name: 'Libertad FC', strength: 69, nation: 'Equador' },
            { name: 'Orense', strength: 69, nation: 'Equador' },
            { name: 'Imbabura', strength: 68, nation: 'Equador' },
            { name: 'Cumbayá', strength: 67, nation: 'Equador' }
        ]
    },
    paraguai: {
        label: 'Liga Paraguai',
        teams: [
            { name: 'Olimpia', strength: 81, nation: 'Paraguai' },
            { name: 'Cerro Porteño', strength: 80, nation: 'Paraguai' },
            { name: 'Libertad', strength: 79, nation: 'Paraguai' },
            { name: 'Guaraní', strength: 76, nation: 'Paraguai' },
            { name: 'Sol de América', strength: 74, nation: 'Paraguai' },
            { name: 'Sportivo Luqueño', strength: 73, nation: 'Paraguai' },
            { name: 'Nacional', strength: 72, nation: 'Paraguai' },
            { name: 'Sportivo Trinidense', strength: 71, nation: 'Paraguai' },
            { name: 'General Caballero JLM', strength: 70, nation: 'Paraguai' },
            { name: 'Tacuary', strength: 70, nation: 'Paraguai' },
            { name: 'Sportivo Ameliano', strength: 70, nation: 'Paraguai' },
            { name: 'Olimpia Asunción', strength: 79, nation: 'Paraguai' },
            { name: 'Cerro de Franco', strength: 69, nation: 'Paraguai' },
            { name: 'Guaireña', strength: 68, nation: 'Paraguai' },
            { name: 'Resistencia', strength: 68, nation: 'Paraguai' },
            { name: 'Deportivo Santaní', strength: 67, nation: 'Paraguai' }
        ]
    },
    peru: {
        label: 'Liga Peru',
        teams: [
            { name: 'Alianza Lima', strength: 79, nation: 'Peru' },
            { name: 'Universitario', strength: 78, nation: 'Peru' },
            { name: 'Sporting Cristal', strength: 80, nation: 'Peru' },
            { name: 'Melgar', strength: 75, nation: 'Peru' },
            { name: 'Cienciano', strength: 73, nation: 'Peru' },
            { name: 'César Vallejo', strength: 74, nation: 'Peru' },
            { name: 'Ayacucho', strength: 71, nation: 'Peru' },
            { name: 'UTC', strength: 70, nation: 'Peru' },
            { name: 'Sport Huancayo', strength: 73, nation: 'Peru' },
            { name: 'Cusco FC', strength: 72, nation: 'Peru' },
            { name: 'Deportivo Garcilaso', strength: 71, nation: 'Peru' },
            { name: 'Alianza Atlético', strength: 70, nation: 'Peru' },
            { name: 'Sport Boys', strength: 70, nation: 'Peru' },
            { name: 'Carlos Mannucci', strength: 69, nation: 'Peru' },
            { name: 'Unión Comercio', strength: 68, nation: 'Peru' },
            { name: 'Atlético Grau', strength: 68, nation: 'Peru' },
            { name: 'Los Chankas', strength: 67, nation: 'Peru' },
            { name: 'Comerciantes Unidos', strength: 67, nation: 'Peru' }
        ]
    },
    uruguai: {
        label: 'Liga Uruguai',
        teams: [
            { name: 'Peñarol', strength: 84, nation: 'Uruguai' },
            { name: 'Nacional', strength: 84, nation: 'Uruguai' },
            { name: 'Defensor Sporting', strength: 77, nation: 'Uruguai' },
            { name: 'Danubio', strength: 74, nation: 'Uruguai' },
            { name: 'Montevideo City', strength: 76, nation: 'Uruguai' },
            { name: 'River Plate', strength: 74, nation: 'Uruguai' },
            { name: 'Wanderers', strength: 73, nation: 'Uruguai' },
            { name: 'Cerro', strength: 72, nation: 'Uruguai' },
            { name: 'Liverpool FC', strength: 77, nation: 'Uruguai' },
            { name: 'Boston River', strength: 73, nation: 'Uruguai' },
            { name: 'Fénix', strength: 71, nation: 'Uruguai' },
            { name: 'Deportivo Maldonado', strength: 70, nation: 'Uruguai' },
            { name: 'Racing de Montevideo', strength: 70, nation: 'Uruguai' },
            { name: 'Progreso', strength: 69, nation: 'Uruguai' },
            { name: 'Miramar Misiones', strength: 68, nation: 'Uruguai' },
            { name: 'Cerro Largo', strength: 68, nation: 'Uruguai' }
        ]
    },
};

export default leagueData;